package de.goork.mapflip.ui

import java.util.Locale

object Strings {

    data class LanguageItem(
        val code: String,
        val nativeName: String,
        val flag: String
    )

    val SUPPORTED_LANGUAGES = listOf(
        LanguageItem("auto", "System", "🌐"),
        LanguageItem("de", "Deutsch", "🇩🇪"),
        LanguageItem("en", "English", "🇺🇸"),
        LanguageItem("da", "Dansk", "🇩🇰"),
        LanguageItem("fr", "Français", "🇫🇷"),
        LanguageItem("it", "Italiano", "🇮🇹"),
        LanguageItem("ja", "日本語", "🇯🇵"),
        LanguageItem("nl", "Nederlands", "🇳🇱"),
        LanguageItem("no", "Norsk", "🇳🇴"),
        LanguageItem("pl", "Polski", "🇵🇱"),
        LanguageItem("pt", "Português", "🇵🇹"),
        LanguageItem("sv", "Svenska", "🇸🇪"),
        LanguageItem("es", "Español", "🇪🇸"),
        LanguageItem("tr", "Türkçe", "🇹🇷"),
        LanguageItem("ko", "한국어", "🇰🇷"),
        LanguageItem("zh", "简体中文", "🇨🇳"),
        LanguageItem("zh-tw", "繁體中文", "🇹🇼"),
        LanguageItem("ar", "العربية", "🇸🇦"),
        LanguageItem("ru", "Русский", "🇷🇺"),
        LanguageItem("id", "Bahasa Indonesia", "🇮🇩")
    )

    data class AppStrings(
        val headline: String,
        val subtitle: String,
        val tagline: String,
        val setupTitle: String,
        val step1: String,
        val step2: String,
        val step3: String,
        val btnSettings: String,
        val statusActive: String,
        val statusInactive: String,
        val statusHint: String,
        val famwakeTitle: String,
        val famwakePromo: String,
        val famwakeDesc: String,
        val famwakeButton: String,
        val copyright: String,
        val langToggle: String,
        val btnFeedback: String,
        val pauseTitle: String,
        val pauseDesc: String,
        val statusPaused: String,
        val selectLanguageTitle: String,
        val systemLanguageAuto: String,
        val btnRateApp: String,
        val privacyNote: String,
        val testLinkTitle: String,
        val testLinkHint: String,
        val btnPasteClipboard: String,
        val btnTestLink: String,
        val testLinkConvertedLabel: String,
        val pauseIndefinitely: String,
        val pause1Hour: String,
        val pause8Hours: String,
        val pauseUntilTomorrow: String,
        val dialogPauseTitle: String,
        val menuSettingsAbout: String,
        val aboutTitle: String,
        val appVersionLabel: String,
        val btnClose: String,
        val sectionLanguage: String,
        val sectionTheme: String,
        val themeSystem: String,
        val themeLight: String,
        val themeDark: String,
        val btnDonate: String,
        val donateSubtitle: String,
        val privacyPolicyTitle: String,
        val sectionGeneral: String,
        val sectionAbout: String,
        val quickGuideTitle: String,
        val sectionTargetApp: String = "Navigation App",
        val targetAppAlwaysAsk: String = "Always ask (System Picker)",
        val btnCopyLink: String = "Copy link",
        val linkCopiedToast: String = "Link copied to clipboard"
    ) {
        fun testButtonLabel(targetApp: de.goork.mapflip.navigation.TargetNavigationApp): String {
            val appName = when (targetApp) {
                de.goork.mapflip.navigation.TargetNavigationApp.GOOGLE_MAPS -> "Google Maps"
                de.goork.mapflip.navigation.TargetNavigationApp.WAZE -> "Waze"
                de.goork.mapflip.navigation.TargetNavigationApp.ORGANIC_MAPS -> "Organic Maps"
                de.goork.mapflip.navigation.TargetNavigationApp.OSMAND -> "OsmAnd"
                de.goork.mapflip.navigation.TargetNavigationApp.SYSTEM_PICKER -> if (sectionTargetApp.isNotBlank()) sectionTargetApp else "Navigation App"
            }
            return try {
                btnTestLink.format(appName)
            } catch (_: Exception) {
                "Test ($appName)"
            }
        }
    }

    fun resolveLanguage(savedPref: String?): String {
        if (!savedPref.isNullOrBlank() && savedPref != "auto") {
            return savedPref
        }
        val locale = Locale.getDefault()
        val lang = locale.language.lowercase()
        val country = locale.country.uppercase()
        if (lang == "zh") {
            return if (country == "TW" || country == "HK" || country == "MO") "zh-tw" else "zh"
        }
        return when (lang) {
            "de", "en", "da", "fr", "it", "ja", "nl", "no", "pl", "pt", "sv", "es", "tr", "ko", "ar", "ru", "id" -> lang
            else -> "en"
        }
    }

    fun getStrings(langCode: String): AppStrings {
        return when (langCode.lowercase()) {
            "de" -> DE
            "en" -> EN
            "da" -> DA
            "fr" -> FR
            "it" -> IT
            "ja" -> JA
            "nl" -> NL
            "no" -> NO
            "pl" -> PL
            "pt" -> PT
            "sv" -> SV
            "es" -> ES
            "tr" -> TR
            "ko" -> KO
            "zh" -> ZH_CN
            "zh-tw" -> ZH_TW
            "ar" -> AR
            "ru" -> RU
            "id" -> ID
            else -> EN
        }
    }

    val DE = AppStrings(
        headline = "MapFlip",
        subtitle = "Apple Maps \u2192 Google Maps",
        tagline = "Automatisch. Unsichtbar.",
        setupTitle = "So geht\u2019s",
        step1 = "Tippe auf den Button \"Einstellungen öffnen\"",
        step2 = "Aktiviere \"Unterst\u00fctzte Links \u00f6ffnen\" f\u00fcr die gew\u00fcnschten Kartendienste (z.B. Apple, Bing, OSM, Yandex)",
        step3 = "Fertig! Karten-Links \u00f6ffnen sich ab jetzt nahtlos in deiner bevorzugten Navigations-App.",
        btnSettings = "Einstellungen \u00f6ffnen",
        statusActive = "Links sind aktiviert",
        statusInactive = "Links sind noch nicht aktiv",
        statusHint = "Auf \u00e4lteren Android-Versionen kann der Status nicht gepr\u00fcft werden.",
        famwakeTitle = "FamWake \u2013 Familienwecker",
        famwakePromo = "Vom gleichen Entwickler",
        famwakeDesc = "FamWake koordiniert den Morgen f\u00fcr die ganze Familie \u2013 Bad-Zeiten, Fr\u00fchst\u00fcck und Aufstehen.",
        famwakeButton = "Mehr erfahren",
        copyright = "\u00a9 2026 Daniel Notthoff",
        langToggle = "DE",
        btnFeedback = "Support",
        pauseTitle = "Weiterleitung pausieren",
        pauseDesc = "Vorübergehend alle Umleitungen aussetzen",
        statusPaused = "Weiterleitung ist pausiert",
        selectLanguageTitle = "Sprache wählen",
        systemLanguageAuto = "Systemstandard (Automatisch)",
        btnRateApp = "App bewerten",
        privacyNote = "100% datenschutzfreundlich: Alle Konvertierungen finden lokal statt. Keine Datenerfassung.",
        testLinkTitle = "Link-Tester & Zwischenablage",
        testLinkHint = "Karten-Link hier eingeben (Apple, Bing, OSM, Yandex)...",
        btnPasteClipboard = "Einfügen",
        btnTestLink = "In %s testen",
        testLinkConvertedLabel = "Umgewandelte Ziel-URI:",
        pauseIndefinitely = "Unbegrenzt",
        pause1Hour = "1 Stunde",
        pause8Hours = "8 Stunden",
        pauseUntilTomorrow = "Bis morgen früh",
        dialogPauseTitle = "Pausendauer wählen",
        menuSettingsAbout = "Einstellungen & Info",
        aboutTitle = "Über MapFlip",
        appVersionLabel = "Version",
        btnClose = "Schließen",
        sectionLanguage = "Sprache",
        sectionTheme = "Erscheinungsbild",
        themeSystem = "Systemstandard",
        themeLight = "Hell",
        themeDark = "Dunkel",
        btnDonate = "Spenden",
        donateSubtitle = "Unterstütze die Entwicklung auf Ko-fi",
        privacyPolicyTitle = "Datenschutzerklärung",
        sectionGeneral = "Allgemein",
        sectionAbout = "Über die App",
        quickGuideTitle = "Kurzanleitung",
        sectionTargetApp = "Ziel-Navigations-App",
        targetAppAlwaysAsk = "Immer fragen (Systemauswahl)",
        btnCopyLink = "Link kopieren",
        linkCopiedToast = "Link in die Zwischenablage kopiert"
    )

    val EN = AppStrings(
        headline = "MapFlip",
        subtitle = "Apple Maps \u2192 Google Maps",
        tagline = "Automatic. Invisible.",
        setupTitle = "How it works",
        step1 = "Tap the \"Open Settings\" button",
        step2 = "Enable \"Open supported links\" for the map services you want (e.g. Apple, Bing, OSM, Yandex)",
        step3 = "Done! Map links will now open seamlessly in your preferred navigation app.",
        btnSettings = "Open Settings",
        statusActive = "Links are enabled",
        statusInactive = "Links are not yet active",
        statusHint = "Status cannot be checked on older Android versions.",
        famwakeTitle = "FamWake \u2013 Family Alarm Clock",
        famwakePromo = "From the same developer",
        famwakeDesc = "FamWake coordinates the morning for the whole family \u2013 bathroom times, breakfast, and wake-up.",
        famwakeButton = "Learn more",
        copyright = "\u00a9 2026 Daniel Notthoff",
        langToggle = "EN",
        btnFeedback = "Support",
        pauseTitle = "Pause Redirect",
        pauseDesc = "Temporarily suspend all link redirects",
        statusPaused = "Redirect is paused",
        selectLanguageTitle = "Select Language",
        systemLanguageAuto = "System Default (Auto)",
        btnRateApp = "Rate App",
        privacyNote = "100% privacy-friendly: All redirects are processed locally. No data collection.",
        testLinkTitle = "Link Tester & Clipboard",
        testLinkHint = "Enter map link here (Apple, Bing, OSM, Yandex)...",
        btnPasteClipboard = "Paste",
        btnTestLink = "Test in %s",
        testLinkConvertedLabel = "Converted Target URI:",
        pauseIndefinitely = "Indefinitely",
        pause1Hour = "1 Hour",
        pause8Hours = "8 Hours",
        pauseUntilTomorrow = "Until tomorrow morning",
        dialogPauseTitle = "Select Pause Duration",
        menuSettingsAbout = "Settings & About",
        aboutTitle = "About MapFlip",
        appVersionLabel = "Version",
        btnClose = "Close",
        sectionLanguage = "Language",
        sectionTheme = "Appearance",
        themeSystem = "System default",
        themeLight = "Light",
        themeDark = "Dark",
        btnDonate = "Donate",
        donateSubtitle = "Support the development on Ko-fi",
        privacyPolicyTitle = "Privacy Policy",
        sectionGeneral = "General",
        sectionAbout = "About",
        quickGuideTitle = "Setup Guide"
    )

    val DA = EN.copy(
        tagline = "Automatisk. Usynlig.",
        setupTitle = "Sådan virker det",
        step1 = "Tryk på knappen \"Åbn indstillinger\"",
        step2 = "Aktivér \"Åbn links\" for maps.apple.com",
        step3 = "Færdig! Apple Maps links åbnes nu automatisk i Google Maps.",
        btnSettings = "Åbn indstillinger",
        statusActive = "Links er aktiveret",
        statusInactive = "Links er endnu ikke aktive",
        statusHint = "Status kan ikke kontrolleres på ældre Android-versioner.",
        famwakeTitle = "FamWake – Familievækkeur",
        famwakePromo = "Fra samme udvikler",
        famwakeDesc = "FamWake koordinerer morgenen for hele familien – badeværelsestider, morgenmad og opvågning.",
        famwakeButton = "Læs mere",
        langToggle = "DA",
        btnFeedback = "Support",
        pauseTitle = "Pausér omdirigering",
        pauseDesc = "Midlertidigt afbryd alle linkomdirigeringer",
        statusPaused = "Omdirigering er sat på pause",
        selectLanguageTitle = "Vælg sprog",
        systemLanguageAuto = "Systemstandard (Automatisk)",
        btnRateApp = "Bedøm app",
        privacyNote = "100% privatlivsvenlig: Alle omdirigeringer sker lokalt. Ingen dataindsamling.",
        testLinkTitle = "Link-tester & udklipsholder",
        testLinkHint = "Indtast Apple Maps-link her...",
        btnPasteClipboard = "Indsæt",
        btnTestLink = "Test i %s",
        testLinkConvertedLabel = "Konverteret mål-URI:",
        pauseIndefinitely = "Ubegrænset",
        pause1Hour = "1 time",
        pause8Hours = "8 timer",
        pauseUntilTomorrow = "Indtil i morgen tidlig",
        dialogPauseTitle = "Vælg pauseduration",
        menuSettingsAbout = "Indstillinger & Om",
        aboutTitle = "Om MapFlip",
        appVersionLabel = "Version",
        btnClose = "Luk",
        sectionLanguage = "Sprog",
        sectionTheme = "Udseende",
        themeSystem = "Systemstandard",
        themeLight = "Lyst",
        themeDark = "Mørkt",
        btnDonate = "Donér",
        donateSubtitle = "Støt udviklingen på Ko-fi",
        privacyPolicyTitle = "Privatlivspolitik",
        sectionGeneral = "Generelt",
        sectionAbout = "Om appen",
        quickGuideTitle = "Startguide",
        btnCopyLink = "Kopier link",
        linkCopiedToast = "Link kopieret til udklipsholder"
    )

    val FR = EN.copy(
        tagline = "Automatique. Invisible.",
        setupTitle = "Comment ça marche",
        step1 = "Appuyez sur le bouton \"Ouvrir les paramètres\"",
        step2 = "Activez \"Ouvrir les liens\" pour maps.apple.com",
        step3 = "Terminé! Les liens Apple Maps s'ouvriront désormais automatiquement dans Google Maps.",
        btnSettings = "Ouvrir les paramètres",
        statusActive = "Les liens sont activés",
        statusInactive = "Les liens ne sont pas encore actifs",
        statusHint = "Le statut ne peut pas être vérifié sur les anciennes versions d'Android.",
        famwakeTitle = "FamWake – Réveil Familial",
        famwakePromo = "Du même développeur",
        famwakeDesc = "FamWake coordonne le matin pour toute la famille – temps de salle de bain, petit-déjeuner et réveil.",
        famwakeButton = "En savoir plus",
        langToggle = "FR",
        btnFeedback = "Support",
        pauseTitle = "Mettre en pause la redirection",
        pauseDesc = "Suspendre temporairement toutes les redirections",
        statusPaused = "La redirection est en pause",
        selectLanguageTitle = "Choisir la langue",
        systemLanguageAuto = "Par défaut du système (Auto)",
        btnRateApp = "Évaluer l'application",
        privacyNote = "100% respectueux de la vie privée : redirection locale, aucune collecte de données.",
        testLinkTitle = "Testeur de liens & presse-papiers",
        testLinkHint = "Entrez le lien Apple Maps ici...",
        btnPasteClipboard = "Coller",
        btnTestLink = "Tester dans %s",
        testLinkConvertedLabel = "URI cible convertie :",
        pauseIndefinitely = "Indéfiniment",
        pause1Hour = "1 heure",
        pause8Hours = "8 heures",
        pauseUntilTomorrow = "Jusqu'à demain matin",
        dialogPauseTitle = "Sélectionner la durée de pause",
        menuSettingsAbout = "Paramètres & À propos",
        aboutTitle = "À propos de MapFlip",
        appVersionLabel = "Version",
        btnClose = "Fermer",
        sectionLanguage = "Langue",
        sectionTheme = "Apparence",
        themeSystem = "Par défaut du système",
        themeLight = "Clair",
        themeDark = "Sombre",
        btnDonate = "Faire un don",
        donateSubtitle = "Soutenir le développement sur Ko-fi",
        privacyPolicyTitle = "Politique de confidentialité",
        sectionGeneral = "Général",
        sectionAbout = "À propos de l'application",
        quickGuideTitle = "Guide de configuration",
        btnCopyLink = "Copier le lien",
        linkCopiedToast = "Lien copié dans le presse-papiers"
    )

    val IT = EN.copy(
        tagline = "Automatico. Invisibile.",
        setupTitle = "Come funziona",
        step1 = "Tocca il pulsante \"Apri Impostazioni\"",
        step2 = "Attiva \"Apri link\" per maps.apple.com",
        step3 = "Fatto! I link di Apple Maps si apriranno ora automaticamente in Google Maps.",
        btnSettings = "Apri Impostazioni",
        statusActive = "I link sono attivi",
        statusInactive = "I link non sono ancora attivi",
        statusHint = "Lo stato non può essere verificato sulle versioni Android meno recenti.",
        famwakeTitle = "FamWake – Sveglia per la Famiglia",
        famwakePromo = "Dallo stesso sviluppatore",
        famwakeDesc = "FamWake coordina il risveglio per tutta la famiglia – turni per il bagno, colazione e sveglia.",
        famwakeButton = "Scopri di più",
        langToggle = "IT",
        btnFeedback = "Supporto",
        pauseTitle = "Pausa reindirizzamento",
        pauseDesc = "Sospendi temporaneamente tutti i reindirizzamenti",
        statusPaused = "Il reindirizzamento è in pausa",
        selectLanguageTitle = "Seleziona lingua",
        systemLanguageAuto = "Predefinita di sistema (Auto)",
        btnRateApp = "Valuta l'app",
        privacyNote = "100% rispetto della privacy: il reindirizzamento avviene localmente. Nessuna raccolta dati.",
        testLinkTitle = "Tester di link e appunti",
        testLinkHint = "Inserisci qui il link di Apple Maps...",
        btnPasteClipboard = "Incolla",
        btnTestLink = "Testa in %s",
        testLinkConvertedLabel = "URI di destinazione convertito:",
        pauseIndefinitely = "A tempo indeterminato",
        pause1Hour = "1 ora",
        pause8Hours = "8 ore",
        pauseUntilTomorrow = "Fino a domani mattina",
        dialogPauseTitle = "Seleziona durata pausa",
        menuSettingsAbout = "Impostazioni e Informazioni",
        aboutTitle = "Informazioni su MapFlip",
        appVersionLabel = "Version",
        btnClose = "Chiudi",
        sectionLanguage = "Lingua",
        sectionTheme = "Aspetto",
        themeSystem = "Predefinito di sistema",
        themeLight = "Chiaro",
        themeDark = "Scuro",
        btnDonate = "Donazione",
        donateSubtitle = "Sostieni lo sviluppo su Ko-fi",
        privacyPolicyTitle = "Informativa sulla privacy",
        sectionGeneral = "Generale",
        sectionAbout = "Informazioni sull'app",
        quickGuideTitle = "Guida introduttiva",
        btnCopyLink = "Copia link",
        linkCopiedToast = "Link copiato negli appunti"
    )

    val JA = EN.copy(
        tagline = "自動。バックグラウンド。",
        setupTitle = "使い方",
        step1 = "「設定を開く」ボタンをタップ",
        step2 = "maps.apple.com の「リンクを開く」を有効化",
        step3 = "完了！Apple Maps のリンクが Google Maps で自動的に開きます。",
        btnSettings = "設定を開く",
        statusActive = "リンク機能は有効です",
        statusInactive = "リンク機能はまだ有効ではありません",
        statusHint = "古い Android バージョンではステータスを確認できません。",
        famwakeTitle = "FamWake – 家族用目覚まし",
        famwakePromo = "同じ開発者によるアプリ",
        famwakeDesc = "FamWakeは家族全員の朝をコーディネート – 洗面所の順番、朝食、起床時間をスマートに管理。",
        famwakeButton = "詳しく見る",
        langToggle = "JA",
        btnFeedback = "サポート",
        pauseTitle = "転送を一時停止",
        pauseDesc = "すべてのリンク転送を一時的に停止します",
        statusPaused = "転送は一時停止中です",
        selectLanguageTitle = "言語を選択",
        systemLanguageAuto = "システムデフォルト (自動)",
        btnRateApp = "アプリを評価する",
        privacyNote = "100% プライバシー保護：転送処理はすべてローカルで行われ、データ収集は一切行いません。",
        testLinkTitle = "リンクテスター＆クリップボード",
        testLinkHint = "Apple Mapsリンクをここに入力...",
        btnPasteClipboard = "貼り付け",
        btnTestLink = "%sでテスト",
        testLinkConvertedLabel = "変換されたターゲットURI:",
        pauseIndefinitely = "無制限",
        pause1Hour = "1時間",
        pause8Hours = "8時間",
        pauseUntilTomorrow = "明日の朝まで",
        dialogPauseTitle = "一時停止期間を選択",
        menuSettingsAbout = "設定と情報",
        aboutTitle = "MapFlipについて",
        appVersionLabel = "バージョン",
        btnClose = "閉じる",
        sectionLanguage = "言語",
        sectionTheme = "テーマ",
        themeSystem = "システムデフォルト",
        themeLight = "ライト",
        themeDark = "ダーク",
        btnDonate = "寄付する",
        donateSubtitle = "Ko-fiで開発をサポート",
        privacyPolicyTitle = "プライバシーポリシー",
        sectionGeneral = "一般",
        sectionAbout = "アプリについて",
        quickGuideTitle = "クイックガイド",
        btnCopyLink = "リンクをコピー",
        linkCopiedToast = "リンクをクリップボードにコピーしました"
    )

    val NL = EN.copy(
        tagline = "Automatisch. Onzichtbaar.",
        setupTitle = "Hoe het werkt",
        step1 = "Tik op de knop \"Instellingen openen\"",
        step2 = "Schakel \"Links openen\" in voor maps.apple.com",
        step3 = "Klaar! Apple Maps-links openen vanaf nu automatisch in Google Maps.",
        btnSettings = "Instellingen openen",
        statusActive = "Links zijn ingeschakeld",
        statusInactive = "Links zijn nog niet actief",
        statusHint = "Status kan niet worden gecontroleerd op oudere Android-versies.",
        famwakeTitle = "FamWake – Familiewekker",
        famwakePromo = "Van dezelfde ontwikkelaar",
        famwakeDesc = "FamWake coördineert de ochtend voor het hele gezin – badkamertijden, ontbijt en opstaan.",
        famwakeButton = "Meer ontdekken",
        langToggle = "NL",
        btnFeedback = "Support",
        pauseTitle = "Omleiding pauzeren",
        pauseDesc = "Tijdelijk alle link-omleidingen onderbreken",
        statusPaused = "Omleiding is gepauzeerd",
        selectLanguageTitle = "Taal selecteren",
        systemLanguageAuto = "Systeemstandaard (Automatisch)",
        btnRateApp = "Beoordeel app",
        privacyNote = "100% privacyvriendelijk: alle omleidingen vinden lokaal plaats. Geen gegevensverzameling.",
        testLinkTitle = "Link-tester & klembord",
        testLinkHint = "Voer hier Apple Maps-link in...",
        btnPasteClipboard = "Plakken",
        btnTestLink = "Testen in %s",
        testLinkConvertedLabel = "Geconverteerde doel-URI:",
        pauseIndefinitely = "Onbeperkt",
        pause1Hour = "1 uur",
        pause8Hours = "8 uur",
        pauseUntilTomorrow = "Tot morgenochtend",
        dialogPauseTitle = "Pauzeduur selecteren",
        menuSettingsAbout = "Instellingen & Over",
        aboutTitle = "Over MapFlip",
        appVersionLabel = "Versie",
        btnClose = "Sluiten",
        sectionLanguage = "Taal",
        sectionTheme = "Weergave",
        themeSystem = "Systeemstandaard",
        themeLight = "Licht",
        themeDark = "Donker",
        btnDonate = "Doneren",
        donateSubtitle = "Ondersteun de ontwikkeling op Ko-fi",
        privacyPolicyTitle = "Privacybeleid",
        sectionGeneral = "Algemeen",
        sectionAbout = "Over de app",
        quickGuideTitle = "Snelstartgids",
        btnCopyLink = "Link kopiëren",
        linkCopiedToast = "Link gekopieerd naar klembord"
    )

    val NO = EN.copy(
        tagline = "Automatisk. Usynlig.",
        setupTitle = "Slik fungerer det",
        step1 = "Trykk på knappen \"Åpne innstillinger\"",
        step2 = "Aktiver \"Åpne lenker\" for maps.apple.com",
        step3 = "Ferdig! Apple Maps-lenker åpnes nå automatisk i Google Maps.",
        btnSettings = "Åpne innstillinger",
        statusActive = "Lenker er aktivert",
        statusInactive = "Lenker er ikke aktive ennå",
        statusHint = "Status kan ikke sjekkes på eldre Android-versjoner.",
        famwakeTitle = "FamWake – Familiealarm",
        famwakePromo = "Fra samme utvikler",
        famwakeDesc = "FamWake koordinerer morgenen for hele familien – baderomstider, frokost og oppvåkning.",
        famwakeButton = "Finn ut mer",
        langToggle = "NO",
        btnFeedback = "Støtte",
        pauseTitle = "Sett viderekobling på pause",
        pauseDesc = "Avbryt midlertidig alle lenke-viderekoblinger",
        statusPaused = "Viderekobling er satt på pause",
        selectLanguageTitle = "Velg språk",
        systemLanguageAuto = "Systemstandard (Automatisk)",
        btnRateApp = "Vurder appen",
        privacyNote = "100% personvernvennlig: Alle viderekoblinger skjer lokalt. Ingen dataindsamling.",
        testLinkTitle = "Lenketester & utklippstavle",
        testLinkHint = "Skriv inn Apple Maps-lenke her...",
        btnPasteClipboard = "Lim inn",
        btnTestLink = "Test i %s",
        testLinkConvertedLabel = "Konvertert mål-URI:",
        pauseIndefinitely = "Ubegrenset",
        pause1Hour = "1 time",
        pause8Hours = "8 timer",
        pauseUntilTomorrow = "Til i morgen tidlig",
        dialogPauseTitle = "Velg pausedurasjon",
        menuSettingsAbout = "Innstillinger og info",
        aboutTitle = "Om MapFlip",
        appVersionLabel = "Versjon",
        btnClose = "Lukk",
        sectionLanguage = "Språk",
        sectionTheme = "Utseende",
        themeSystem = "Systemstandard",
        themeLight = "Lyst",
        themeDark = "Mørkt",
        btnDonate = "Doner",
        donateSubtitle = "Støtt utviklingen på Ko-fi",
        privacyPolicyTitle = "Personvernerklæring",
        sectionGeneral = "Generelt",
        sectionAbout = "Om appen",
        quickGuideTitle = "Hurtigveiledning",
        btnCopyLink = "Kopier lenke",
        linkCopiedToast = "Lenke kopiert til utklippstavlen"
    )

    val PL = EN.copy(
        tagline = "Automatycznie. Niewidocznie.",
        setupTitle = "Jak to działa",
        step1 = "Dotknij przycisku \"Otwórz ustawienia\"",
        step2 = "Włącz \"Otwieraj linki\" dla maps.apple.com",
        step3 = "Gotowe! Linki Apple Maps będą teraz automatycznie otwierać się w Google Maps.",
        btnSettings = "Otwórz ustawienia",
        statusActive = "Linki są włączone",
        statusInactive = "Linki nie są jeszcze aktywne",
        statusHint = "Nie można sprawdzić stanu na starszych wersjach systemu Android.",
        famwakeTitle = "FamWake – Budzik Rodzinny",
        famwakePromo = "Od tego samego twórcy",
        famwakeDesc = "FamWake koordynuje poranki dla całej rodziny – kolejka do łazienki, śniadanie i pobudka.",
        famwakeButton = "Dowiedz się więcej",
        langToggle = "PL",
        btnFeedback = "Pomoc",
        pauseTitle = "Wstrzymaj przekierowanie",
        pauseDesc = "Tymczasowo zawieś wszystkie przekierowania",
        statusPaused = "Przekierowanie jest wstrzymane",
        selectLanguageTitle = "Wybierz język",
        systemLanguageAuto = "Domyślny systemu (Auto)",
        btnRateApp = "Oceń aplikację",
        privacyNote = "100% prywatności: wszystkie przekierowania odbywają się lokalnie. Brak zbierania danych.",
        testLinkTitle = "Tester linków i schowek",
        testLinkHint = "Wpisz tutaj link Apple Maps...",
        btnPasteClipboard = "Wklej",
        btnTestLink = "Testuj w %s",
        testLinkConvertedLabel = "Przekonwertowany URI docelowy:",
        pauseIndefinitely = "Na czas nieokreślony",
        pause1Hour = "1 godzina",
        pause8Hours = "8 godzin",
        pauseUntilTomorrow = "Do jutra rano",
        dialogPauseTitle = "Wybierz czas wstrzymania",
        menuSettingsAbout = "Ustawienia i informacje",
        aboutTitle = "O aplikacji MapFlip",
        appVersionLabel = "Wersja",
        btnClose = "Zamknij",
        sectionLanguage = "Język",
        sectionTheme = "Wygląd",
        themeSystem = "Domyślny systemu",
        themeLight = "Jasny",
        themeDark = "Ciemny",
        btnDonate = "Wesprzyj",
        donateSubtitle = "Wesprzyj rozwój na Ko-fi",
        privacyPolicyTitle = "Polityka prywatności",
        sectionGeneral = "Ogólne",
        sectionAbout = "O aplikacji",
        quickGuideTitle = "Szybki przewodnik",
        btnCopyLink = "Kopiuj link",
        linkCopiedToast = "Link skopiowany do schowka"
    )

    val PT = EN.copy(
        tagline = "Automático. Invisível.",
        setupTitle = "Como funciona",
        step1 = "Toque no botão \"Abrir Configurações\"",
        step2 = "Ative \"Abrir links\" para maps.apple.com",
        step3 = "Concluído! Os links do Apple Maps serão abertos automaticamente no Google Maps.",
        btnSettings = "Abrir Configurações",
        statusActive = "Links estão ativados",
        statusInactive = "Links ainda não estão ativos",
        statusHint = "O status não pode ser verificado em versões anteriores do Android.",
        famwakeTitle = "FamWake – Despertador Familiar",
        famwakePromo = "Do mesmo desenvolvedor",
        famwakeDesc = "O FamWake coordena as manhãs de toda a família – horários de casa de banho, pequeno-almoço e acordar.",
        famwakeButton = "Saber mais",
        langToggle = "PT",
        btnFeedback = "Suporte",
        pauseTitle = "Pausar redirecionamento",
        pauseDesc = "Suspender temporariamente todos os redirecionamentos",
        statusPaused = "O redirecionamento está pausado",
        selectLanguageTitle = "Selecionar idioma",
        systemLanguageAuto = "Padrão do sistema (Auto)",
        btnRateApp = "Avaliar app",
        privacyNote = "100% privacidade: todos os redirecionamentos ocorrem localmente. Sem coleta de dados.",
        testLinkTitle = "Testador de links e área de transferência",
        testLinkHint = "Digite o link do Apple Maps aqui...",
        btnPasteClipboard = "Colar",
        btnTestLink = "Testar no %s",
        testLinkConvertedLabel = "URI de destino convertido:",
        pauseIndefinitely = "Indefinidamente",
        pause1Hour = "1 hora",
        pause8Hours = "8 horas",
        pauseUntilTomorrow = "Até amanhã de manhã",
        dialogPauseTitle = "Selecionar duração da pausa",
        menuSettingsAbout = "Configurações e Sobre",
        aboutTitle = "Sobre o MapFlip",
        appVersionLabel = "Versão",
        btnClose = "Fechar",
        sectionLanguage = "Idioma",
        sectionTheme = "Aparência",
        themeSystem = "Padrão do sistema",
        themeLight = "Claro",
        themeDark = "Escuro",
        btnDonate = "Doar",
        donateSubtitle = "Apoie o desenvolvimento no Ko-fi",
        privacyPolicyTitle = "Política de Privacidade",
        sectionGeneral = "Geral",
        sectionAbout = "Sobre a aplicação",
        quickGuideTitle = "Guia rápido",
        btnCopyLink = "Copiar link",
        linkCopiedToast = "Link copiado para a área de transferência"
    )

    val SV = EN.copy(
        tagline = "Automatiskt. Osynligt.",
        setupTitle = "Hur det fungerar",
        step1 = "Tryck på knappen \"Öppna inställningar\"",
        step2 = "Aktivera \"Öppna länkar\" för maps.apple.com",
        step3 = "Klart! Apple Maps-länkar öppnas nu automatiskt i Google Maps.",
        btnSettings = "Öppna inställningar",
        statusActive = "Länkar är aktiverade",
        statusInactive = "Länkar är inte aktiva än",
        statusHint = "Status kan inte kontrolleras på äldre Android-versioner.",
        famwakeTitle = "FamWake – Familjeväckarklocka",
        famwakePromo = "Från samma utvecklare",
        famwakeDesc = "FamWake samordnar morgonen för hela familjen – badrumstider, frukost och uppstigning.",
        famwakeButton = "Läs mer",
        langToggle = "SV",
        btnFeedback = "Support",
        pauseTitle = "Pausa omdirigering",
        pauseDesc = "Avbryt tillfälligt alla länkomdirigeringar",
        statusPaused = "Omdirigering är pausad",
        selectLanguageTitle = "Välj språk",
        systemLanguageAuto = "Systemstandard (Automatisk)",
        btnRateApp = "Betygsätt appen",
        privacyNote = "100% integritetsvänlig: alla omdirigeringar sker lokalt. Ingen dataindsamling.",
        testLinkTitle = "Länktester & urklipp",
        testLinkHint = "Ange Apple Maps-länk här...",
        btnPasteClipboard = "Klistra in",
        btnTestLink = "Testa i %s",
        testLinkConvertedLabel = "Konverterad mål-URI:",
        pauseIndefinitely = "Tills vidare",
        pause1Hour = "1 timme",
        pause8Hours = "8 timmar",
        pauseUntilTomorrow = "Till imorgon bitti",
        dialogPauseTitle = "Välj pauslängd",
        menuSettingsAbout = "Inställningar och Om",
        aboutTitle = "Om MapFlip",
        appVersionLabel = "Version",
        btnClose = "Stäng",
        sectionLanguage = "Språk",
        sectionTheme = "Utseende",
        themeSystem = "Systemstandard",
        themeLight = "Ljust",
        themeDark = "Mørkt",
        btnDonate = "Donera",
        donateSubtitle = "Stöd utvecklingen på Ko-fi",
        privacyPolicyTitle = "Integritetspolicy",
        sectionGeneral = "Allmänt",
        sectionAbout = "Om appen",
        quickGuideTitle = "Snabbguide",
        btnCopyLink = "Kopiera länk",
        linkCopiedToast = "Länk kopierad till urklipp"
    )

    val ES = EN.copy(
        tagline = "Automático. Invisible.",
        setupTitle = "Cómo funciona",
        step1 = "Toca el botón \"Abrir Ajustes\"",
        step2 = "Activa \"Abrir enlaces\" para maps.apple.com",
        step3 = "¡Listo! Los enlaces de Apple Maps se abrirán automáticamente en Google Maps.",
        btnSettings = "Abrir Ajustes",
        statusActive = "Los enlaces están activados",
        statusInactive = "Los enlaces aún no están activos",
        statusHint = "El estado no se puede verificar en versiones anteriores de Android.",
        famwakeTitle = "FamWake – Despertador Familiar",
        famwakePromo = "Del mismo desarrollador",
        famwakeDesc = "FamWake coordina las mañanas de toda la familia: turnos de baño, desayuno y despertar.",
        famwakeButton = "Más información",
        langToggle = "ES",
        btnFeedback = "Soporte",
        pauseTitle = "Pausar redirección",
        pauseDesc = "Suspender temporalmente todas las redirecciones de enlaces",
        statusPaused = "La redirección está pausada",
        selectLanguageTitle = "Seleccionar idioma",
        systemLanguageAuto = "Predeterminado del sistema (Auto)",
        btnRateApp = "Calificar app",
        privacyNote = "100% privado: todas las redirecciones se procesan localmente. Sin recopilación de datos.",
        testLinkTitle = "Probador de enlaces y portapapeles",
        testLinkHint = "Introduce aquí el enlace de Apple Maps...",
        btnPasteClipboard = "Pegar",
        btnTestLink = "Probar en %s",
        testLinkConvertedLabel = "URI de destino convertida:",
        pauseIndefinitely = "Indefinidamente",
        pause1Hour = "1 hora",
        pause8Hours = "8 horas",
        pauseUntilTomorrow = "Hasta mañana por la mañana",
        dialogPauseTitle = "Seleccionar duración de pausa",
        menuSettingsAbout = "Ajustes e Información",
        aboutTitle = "Acerca de MapFlip",
        appVersionLabel = "Versión",
        btnClose = "Cerrar",
        sectionLanguage = "Idioma",
        sectionTheme = "Apariencia",
        themeSystem = "Predeterminado del sistema",
        themeLight = "Claro",
        themeDark = "Oscuro",
        btnDonate = "Donar",
        donateSubtitle = "Apoya el desarrollo en Ko-fi",
        privacyPolicyTitle = "Política de privacidad",
        sectionGeneral = "General",
        sectionAbout = "Acerca de la app",
        quickGuideTitle = "Guía rápida",
        btnCopyLink = "Copiar enlace",
        linkCopiedToast = "Enlace copiado al portapapeles"
    )

    val TR = EN.copy(
        tagline = "Otomatik. Görünmez.",
        setupTitle = "Nasıl çalışır",
        step1 = "Aşağıdaki \"Ayarları Aç\" düğmesine dokunun",
        step2 = "maps.apple.com için \"Bağlantıları aç\"ı etkinleştirin",
        step3 = "Bitti! Apple Maps bağlantıları artık Google Maps'te otomatik açılacak.",
        btnSettings = "Ayarları Aç",
        statusActive = "Bağlantılar etkinleştirildi",
        statusInactive = "Bağlantılar henüz etkin değil",
        statusHint = "Eski Android sürümlerinde durum kontrol edilemez.",
        famwakeTitle = "FamWake – Aile Çalar Saati",
        famwakePromo = "Aynı geliştiriciden",
        famwakeDesc = "FamWake tüm aile için sabahı koordine eder – banyo saatleri, kahvaltı ve uyanma.",
        famwakeButton = "Daha fazla bilgi",
        langToggle = "TR",
        btnFeedback = "Destek",
        pauseTitle = "Yönlendirmeyi Duraklat",
        pauseDesc = "Tüm bağlantı yönlendirmelerini geçici olarak durdurun",
        statusPaused = "Yönlendirme duraklatıldı",
        selectLanguageTitle = "Dil Seçin",
        systemLanguageAuto = "Sistem Varsayılanı (Otomatik)",
        btnRateApp = "Uygulamayı değerlendir",
        privacyNote = "100% gizlilik dostu: Tüm yönlendirmeler yerel olarak yapılır. Veri toplama yoktur.",
        testLinkTitle = "Bağlantı Test Edici ve Pano",
        testLinkHint = "Buraya Apple Maps bağlantısını girin...",
        btnPasteClipboard = "Yapıştır",
        btnTestLink = "%s'te Test Et",
        testLinkConvertedLabel = "Dönüştürülen Hedef URI:",
        pauseIndefinitely = "Süresiz",
        pause1Hour = "1 Saat",
        pause8Hours = "8 Saat",
        pauseUntilTomorrow = "Yarın sabaha kadar",
        dialogPauseTitle = "Duraklatma Süresi Seçin",
        menuSettingsAbout = "Ayarlar & Hakkında",
        aboutTitle = "MapFlip Hakkında",
        appVersionLabel = "Sürüm",
        btnClose = "Kapat",
        sectionLanguage = "Dil",
        sectionTheme = "Görünüm",
        themeSystem = "Sistem varsayılanı",
        themeLight = "Açık",
        themeDark = "Koyu",
        btnDonate = "Bağış Yap",
        donateSubtitle = "Geliştirmeyi Ko-fi üzerinden destekleyin",
        privacyPolicyTitle = "Gizlilik Politikası",
        sectionGeneral = "Genel",
        sectionAbout = "Uygulama hakkında",
        quickGuideTitle = "Kurulum Kılavuzu",
        btnCopyLink = "Bağlantıyı kopyala",
        linkCopiedToast = "Bağlantı panoya kopyalandı"
    )

    val KO = EN.copy(
        tagline = "자동. 투명함.",
        setupTitle = "설정 방법",
        step1 = "\"설정 열기\" 버튼을 탭하세요",
        step2 = "maps.apple.com에 대해 \"지원되는 링크 열기\"를 활성화하세요",
        step3 = "완료! 이제 Apple Maps 링크가 Google Maps에서 자동으로 열립니다.",
        btnSettings = "설정 열기",
        statusActive = "링크가 활성화되었습니다",
        statusInactive = "링크가 아직 활성화되지 않았습니다",
        statusHint = "이전 Android 버전에서는 상태를 확인할 수 없습니다.",
        famwakeTitle = "FamWake – 패밀리 알람 시계",
        famwakePromo = "동일한 개발자의 추천 앱",
        famwakeDesc = "FamWake는 욕실 사용 순서, 아침 식사, 기상 시간 등 온 가족의 아침 일과를 조율합니다.",
        famwakeButton = "자세히 알아보기",
        langToggle = "KO",
        btnFeedback = "지원 및 문의",
        pauseTitle = "리디렉션 일시중지",
        pauseDesc = "모든 지도 링크 리디렉션을 일시적으로 중지합니다",
        statusPaused = "리디렉션이 일시중지됨",
        selectLanguageTitle = "언어 선택",
        systemLanguageAuto = "시스템 기본값 (자동)",
        btnRateApp = "앱 평가하기",
        privacyNote = "100% 개인정보 보호: 모든 링크는 기기 내에서 로컬로 변환되며 데이터를 수집하지 않습니다.",
        testLinkTitle = "링크 테스터 및 클립보드",
        testLinkHint = "Apple Maps 링크를 여기에 입력하세요...",
        btnPasteClipboard = "붙여넣기",
        btnTestLink = "%s에서 테스트",
        testLinkConvertedLabel = "변환된 대상 URI:",
        pauseIndefinitely = "무기한",
        pause1Hour = "1시간",
        pause8Hours = "8시간",
        pauseUntilTomorrow = "내일 아침까지",
        dialogPauseTitle = "일시중지 시간 선택",
        menuSettingsAbout = "설정 및 정보",
        aboutTitle = "MapFlip 정보",
        appVersionLabel = "버전",
        btnClose = "닫기",
        sectionLanguage = "언어",
        sectionTheme = "화면 테마",
        themeSystem = "시스템 기본값",
        themeLight = "라이트 모드",
        themeDark = "다크 모드",
        btnDonate = "후원하기",
        donateSubtitle = "Ko-fi에서 개발 후원하기",
        privacyPolicyTitle = "개인정보 처리방침",
        sectionGeneral = "일반",
        sectionAbout = "앱 정보",
        quickGuideTitle = "빠른 시작 가이드",
        btnCopyLink = "링크 복사",
        linkCopiedToast = "링크가 클립보드에 복사되었습니다"
    )

    val ZH_CN = EN.copy(
        tagline = "自动。无缝。",
        setupTitle = "使用方法",
        step1 = "点击“打开设置”按钮",
        step2 = "为 maps.apple.com 启用“打开支持的链接”",
        step3 = "完成！Apple Maps 链接将自动在 Google Maps 中打开。",
        btnSettings = "打开设置",
        statusActive = "链接已启用",
        statusInactive = "链接尚未激活",
        statusHint = "旧版 Android 无法检查此状态。",
        famwakeTitle = "FamWake – 家庭早晨闹钟",
        famwakePromo = "同一开发者出品",
        famwakeDesc = "FamWake 协调全家人的清晨节奏 – 洗漱轮流、早餐与起床时间安排。",
        famwakeButton = "了解更多",
        langToggle = "ZH",
        btnFeedback = "技术支持",
        pauseTitle = "暂停重定向",
        pauseDesc = "暂时停用所有地图链接重定向",
        statusPaused = "重定向已暂停",
        selectLanguageTitle = "选择语言",
        systemLanguageAuto = "系统默认（自动）",
        btnRateApp = "评价应用",
        privacyNote = "100% 保护隐私：所有链接均在本地转换，不收集任何数据。",
        testLinkTitle = "链接测试与剪贴板",
        testLinkHint = "在此输入 Apple Maps 链接...",
        btnPasteClipboard = "粘贴",
        btnTestLink = "在 %s 中测试",
        testLinkConvertedLabel = "转换后的目标 URI:",
        pauseIndefinitely = "无限期",
        pause1Hour = "1 小时",
        pause8Hours = "8 小时",
        pauseUntilTomorrow = "直到明早",
        dialogPauseTitle = "选择暂停时长",
        menuSettingsAbout = "设置与关于",
        aboutTitle = "关于 MapFlip",
        appVersionLabel = "版本",
        btnClose = "关闭",
        sectionLanguage = "语言",
        sectionTheme = "外观",
        themeSystem = "跟随系统",
        themeLight = "浅色",
        themeDark = "深色",
        btnDonate = "赞助支持",
        donateSubtitle = "在 Ko-fi 上支持开发者",
        privacyPolicyTitle = "隐私政策",
        sectionGeneral = "通用",
        sectionAbout = "关于应用",
        quickGuideTitle = "快速指南",
        btnCopyLink = "复制链接",
        linkCopiedToast = "链接已复制到剪贴板"
    )

    val ZH_TW = EN.copy(
        tagline = "自動。無縫。",
        setupTitle = "使用步驟",
        step1 = "點擊「開啟設定」按鈕",
        step2 = "為 maps.apple.com 啟用「開啟支援的連結」",
        step3 = "完成！Apple Maps 連結將自動在 Google Maps 中開啟。",
        btnSettings = "開啟設定",
        statusActive = "連結已啟用",
        statusInactive = "連結尚未啟用",
        statusHint = "舊版 Android 無法檢查此狀態。",
        famwakeTitle = "FamWake – 家庭早晨鬧鐘",
        famwakePromo = "同位開發者推薦",
        famwakeDesc = "FamWake 協調整個家庭的早晨節奏 – 盥洗順序、早餐與起床時間安排。",
        famwakeButton = "了解更多",
        langToggle = "ZH-TW",
        btnFeedback = "技術支援",
        pauseTitle = "暫停重新導向",
        pauseDesc = "暫時停止所有地圖連結轉向",
        statusPaused = "重新導向已暫停",
        selectLanguageTitle = "選擇語言",
        systemLanguageAuto = "系統預設（自動）",
        btnRateApp = "為應用評分",
        privacyNote = "100% 重視隱私：所有轉換均在裝置本機完成，絕不收集任何資料。",
        testLinkTitle = "連結測試與剪貼簿",
        testLinkHint = "在此輸入 Apple Maps 連結...",
        btnPasteClipboard = "貼上",
        btnTestLink = "在 %s 中測試",
        testLinkConvertedLabel = "轉換後的目標 URI:",
        pauseIndefinitely = "無限期",
        pause1Hour = "1 小時",
        pause8Hours = "8 小時",
        pauseUntilTomorrow = "直到明天早上",
        dialogPauseTitle = "選擇暫停時間",
        menuSettingsAbout = "設定與關於",
        aboutTitle = "關於 MapFlip",
        appVersionLabel = "版本",
        btnClose = "關閉",
        sectionLanguage = "語言",
        sectionTheme = "外觀",
        themeSystem = "系統預設",
        themeLight = "淺色",
        themeDark = "深色",
        btnDonate = "贊助支持",
        donateSubtitle = "在 Ko-fi 上支持開發者",
        privacyPolicyTitle = "隱私權政策",
        sectionGeneral = "一般",
        sectionAbout = "關於應用程式",
        quickGuideTitle = "快速上手",
        btnCopyLink = "複製連結",
        linkCopiedToast = "連結已複製到剪貼簿"
    )

    val AR = EN.copy(
        tagline = "تلقائي. غير مرئي.",
        setupTitle = "كيفية البدء",
        step1 = "اضغط على زر \"فتح الإعدادات\"",
        step2 = "فعّل \"فتح الروابط المعتمدة\" لـ maps.apple.com",
        step3 = "تم! ستفتح روابط Apple Maps تلقائياً في Google Maps.",
        btnSettings = "فتح الإعدادات",
        statusActive = "الروابط مفعلة",
        statusInactive = "الروابط غير مفعلة بعد",
        statusHint = "لا يمكن التحقق من الحالة في إصدارات أندرويد القديمة.",
        famwakeTitle = "FamWake – منبه العائلة الذكي",
        famwakePromo = "من نفس المطور",
        famwakeDesc = "ينسّق تطبيق FamWake صباح العائلة بأكملها – مواعيد الحمام والإفطار والاستيقاظ.",
        famwakeButton = "اكتشف المزيد",
        langToggle = "AR",
        btnFeedback = "الدعم والمساعدة",
        pauseTitle = "إيقاف مؤقت لإعادة التوجيه",
        pauseDesc = "تعطيل إعادة التوجيه مؤقتاً لجميع الروابط",
        statusPaused = "إعادة التوجيه متوقفة مؤقتاً",
        selectLanguageTitle = "اختر اللغة",
        systemLanguageAuto = "افتراضي النظام (تلقائي)",
        btnRateApp = "تقييم التطبيق",
        privacyNote = "خصوصية 100%: تتم جميع التحويلات محلياً على جهازك دون جمع أي بيانات.",
        testLinkTitle = "اختبار الروابط والحافظة",
        testLinkHint = "أدخل رابط Apple Maps هنا...",
        btnPasteClipboard = "لصق",
        btnTestLink = "اختبار في %s",
        testLinkConvertedLabel = "الرابط الهدف المحول:",
        pauseIndefinitely = "إلى أجل غير مسمى",
        pause1Hour = "ساعة واحدة",
        pause8Hours = "8 ساعات",
        pauseUntilTomorrow = "حتى صباح الغد",
        dialogPauseTitle = "اختر مدة الإيقاف المؤقت",
        menuSettingsAbout = "الإعدادات وحول التطبيق",
        aboutTitle = "حول MapFlip",
        appVersionLabel = "الإصدار",
        btnClose = "إغلاق",
        sectionLanguage = "اللغة",
        sectionTheme = "المظهر",
        themeSystem = "افتراضي النظام",
        themeLight = "فاتح",
        themeDark = "داكن",
        btnDonate = "تبرع",
        donateSubtitle = "ادعم التطوير على Ko-fi",
        privacyPolicyTitle = "سياسة الخصوصية",
        sectionGeneral = "عام",
        sectionAbout = "حول التطبيق",
        quickGuideTitle = "دليل الإعداد السريع",
        btnCopyLink = "نسخ الرابط",
        linkCopiedToast = "تم نسخ الرابط إلى الحافظة"
    )

    val RU = EN.copy(
        tagline = "Автоматически. Незаметно.",
        setupTitle = "Как это работает",
        step1 = "Нажмите кнопку «Открыть настройки»",
        step2 = "Включите «Открывать поддерживаемые ссылки» для maps.apple.com",
        step3 = "Готово! Ссылки Apple Maps теперь автоматически открываются в Google Maps.",
        btnSettings = "Открыть настройки",
        statusActive = "Ссылки включены",
        statusInactive = "Ссылки еще не активны",
        statusHint = "Статус нельзя проверить на старых версиях Android.",
        famwakeTitle = "FamWake – Семейный будильник",
        famwakePromo = "От того же разработчика",
        famwakeDesc = "FamWake координирует утро для всей семьи — очередь в ванную, завтрак и подъем.",
        famwakeButton = "Узнать больше",
        langToggle = "RU",
        btnFeedback = "Поддержка",
        pauseTitle = "Приостановить перенаправление",
        pauseDesc = "Временно отключить все перенаправления ссылок",
        statusPaused = "Перенаправление приостановлено",
        selectLanguageTitle = "Выбрать язык",
        systemLanguageAuto = "Системный (авто)",
        btnRateApp = "Оценить приложение",
        privacyNote = "100% конфиденциальность: вся обработка выполняется локально на устройстве. Без сбора данных.",
        testLinkTitle = "Тестер ссылок и буфер обмена",
        testLinkHint = "Введите ссылку Apple Maps здесь...",
        btnPasteClipboard = "Вставить",
        btnTestLink = "Проверить в %s",
        testLinkConvertedLabel = "Преобразованный URI:",
        pauseIndefinitely = "Бессрочно",
        pause1Hour = "1 час",
        pause8Hours = "8 часов",
        pauseUntilTomorrow = "До завтрашнего утра",
        dialogPauseTitle = "Выберите время паузы",
        menuSettingsAbout = "Настройки и о приложении",
        aboutTitle = "О приложении MapFlip",
        appVersionLabel = "Версия",
        btnClose = "Закрыть",
        sectionLanguage = "Язык",
        sectionTheme = "Тема оформления",
        themeSystem = "Системная",
        themeLight = "Светлая",
        themeDark = "Темная",
        btnDonate = "Поддержать",
        donateSubtitle = "Поддержать разработку на Ko-fi",
        privacyPolicyTitle = "Политика конфиденциальности",
        sectionGeneral = "Общие",
        sectionAbout = "О приложении",
        quickGuideTitle = "Инструкция",
        btnCopyLink = "Скопировать ссылку",
        linkCopiedToast = "Ссылка скопирована в буфер обмена"
    )

    val ID = EN.copy(
        tagline = "Otomatis. Tak Terlihat.",
        setupTitle = "Cara Penggunaan",
        step1 = "Ketuk tombol \"Buka Pengaturan\"",
        step2 = "Aktifkan \"Buka tautan yang didukung\" untuk maps.apple.com",
        step3 = "Selesai! Tautan Apple Maps akan otomatis dibuka di Google Maps.",
        btnSettings = "Buka Pengaturan",
        statusActive = "Tautan aktif",
        statusInactive = "Tautan belum aktif",
        statusHint = "Status tidak dapat diperiksa pada versi Android lama.",
        famwakeTitle = "FamWake – Jam Weker Keluarga",
        famwakePromo = "Dari pengembang yang sama",
        famwakeDesc = "FamWake mengoordinasikan pagi untuk seluruh keluarga – giliran kamar mandi, sarapan, dan bangun tidur.",
        famwakeButton = "Pelajari selengkapnya",
        langToggle = "ID",
        btnFeedback = "Bantuan & Dukungan",
        pauseTitle = "Jeda Pengalihan",
        pauseDesc = "Hentikan sementara semua pengalihan tautan peta",
        statusPaused = "Pengalihan dijeda",
        selectLanguageTitle = "Pilih Bahasa",
        systemLanguageAuto = "Default Sistem (Otomatis)",
        btnRateApp = "Beri Nilai Aplikasi",
        privacyNote = "100% ramah privasi: Semua konversi diproses secara lokal di perangkat. Tanpa pengumpulan data.",
        testLinkTitle = "Penguji Tautan & Papan Klip",
        testLinkHint = "Masukkan tautan Apple Maps di sini...",
        btnPasteClipboard = "Tempel",
        btnTestLink = "Uji di %s",
        testLinkConvertedLabel = "URI Tujuan Terkonversi:",
        pauseIndefinitely = "Tanpa batas",
        pause1Hour = "1 Jam",
        pause8Hours = "8 Jam",
        pauseUntilTomorrow = "Hingga besok pagi",
        dialogPauseTitle = "Pilih Durasi Jeda",
        menuSettingsAbout = "Pengaturan & Info",
        aboutTitle = "Tentang MapFlip",
        appVersionLabel = "Versi",
        btnClose = "Tutup",
        sectionLanguage = "Bahasa",
        sectionTheme = "Tampilan",
        themeSystem = "Default sistem",
        themeLight = "Terang",
        themeDark = "Gelap",
        btnDonate = "Donasi",
        donateSubtitle = "Dukung pengembangan di Ko-fi",
        privacyPolicyTitle = "Kebijakan Privasi",
        sectionGeneral = "Umum",
        sectionAbout = "Tentang aplikasi",
        quickGuideTitle = "Panduan Penyiapan",
        btnCopyLink = "Salin tautan",
        linkCopiedToast = "Tautan disalin ke papan klip"
    )
}
