package de.goork.mapflip.ui

import java.util.Locale

object Strings {

    data class LanguageItem(
        val code: String,
        val nativeName: String,
        val flag: String
    )

    val SUPPORTED_LANGUAGES = listOf(
        LanguageItem("auto", "System", "🌐"),
        LanguageItem("de", "Deutsch", "🇩🇪"),
        LanguageItem("en", "English", "🇺🇸"),
        LanguageItem("da", "Dansk", "🇩🇰"),
        LanguageItem("fr", "Français", "🇫🇷"),
        LanguageItem("it", "Italiano", "🇮🇹"),
        LanguageItem("ja", "日本語", "🇯🇵"),
        LanguageItem("nl", "Nederlands", "🇳🇱"),
        LanguageItem("no", "Norsk", "🇳🇴"),
        LanguageItem("pl", "Polski", "🇵🇱"),
        LanguageItem("pt", "Português", "🇵🇹"),
        LanguageItem("sv", "Svenska", "🇸🇪"),
        LanguageItem("es", "Español", "🇪🇸"),
        LanguageItem("tr", "Türkçe", "🇹🇷"),
        LanguageItem("ko", "한국어", "🇰🇷"),
        LanguageItem("zh", "简体中文", "🇨🇳"),
        LanguageItem("zh-tw", "繁體中文", "🇹🇼"),
        LanguageItem("ar", "العربية", "🇸🇦"),
        LanguageItem("ru", "Русский", "🇷🇺"),
        LanguageItem("id", "Bahasa Indonesia", "🇮🇩")
    )

    data class AppStrings(
        val headline: String,
        val subtitle: String,
        val tagline: String,
        val setupTitle: String,
        val step1: String,
        val step2: String,
        val step3: String,
        val btnSettings: String,
        val statusActive: String,
        val statusInactive: String,
        val statusHint: String,
        val famwakeTitle: String,
        val famwakePromo: String,
        val famwakeDesc: String,
        val famwakeButton: String,
        val copyright: String,
        val langToggle: String,
        val btnFeedback: String,
        val pauseTitle: String,
        val pauseDesc: String,
        val statusPaused: String,
        val selectLanguageTitle: String,
        val systemLanguageAuto: String,
        val btnRateApp: String,
        val privacyNote: String,
        val privacyNotePlay: String = "",
        val testLinkTitle: String,
        val testLinkHint: String,
        val btnPasteClipboard: String,
        val btnTestLink: String,
        val testLinkConvertedLabel: String,
        val pauseIndefinitely: String,
        val pause1Hour: String,
        val pause8Hours: String,
        val pauseUntilTomorrow: String,
        val dialogPauseTitle: String,
        val menuSettingsAbout: String,
        val aboutTitle: String,
        val appVersionLabel: String,
        val btnClose: String,
        val sectionLanguage: String,
        val sectionTheme: String,
        val themeSystem: String,
        val themeLight: String,
        val themeDark: String,
        val btnDonate: String,
        val donateSubtitle: String,
        val privacyPolicyTitle: String,
        val impressumTitle: String = "Legal Notice (Impressum)",
        val sectionGeneral: String,
        val sectionAbout: String,
        val quickGuideTitle: String,
        val sectionTargetApp: String = "Navigation App",
        val targetAppAlwaysAsk: String = "Always ask (System Picker)",
        val btnCopyLink: String = "Copy link",
        val linkCopiedToast: String = "Link copied to clipboard",
        val btnShareLink: String = "Share link",
        val btnClearInput: String = "Clear",
        val clipboardDetectedTitle: String = "Map link in clipboard",
        val btnOpenInApp: String = "Open in %s",
        val actionExpand: String = "Expand",
        val actionCollapse: String = "Collapse",
        val appNotInstalled: String = "%s is not installed",
        val targetAppOpenError: String = "Target app could not be opened",
        val statusInstalled: String = "Installed",
        val statusNotInstalled: String = "Not installed",
        val tileSetupRequired: String = "Setup required",
        val targetAppFallbackOpened: String = "%s is not installed – opened with %s",
        val redirectingToApp: String = "Redirecting to %s...",
        val setupSheetTitle: String = "Set up map links",
        val setupSheetSubtitle: String = "Android 12+ requires confirming supported map links manually.",
        val setupStep1Title: String = "Open system settings",
        val setupStep1Desc: String = "Tap the button below to open MapFlip's app settings.",
        val setupStep2Title: String = "Select \"Open by default\"",
        val setupStep2Desc: String = "Tap \"Open supported links\" or \"Add links\".",
        val setupStep3Title: String = "Enable map links",
        val setupStep3Desc: String = "Check all supported map domains (Apple Maps, Bing, OSM, HERE etc.).",
        val setupAltTitle: String = "Works immediately without setup:",
        val setupAltShare: String = "Share Menu: Share any map link via Android's Share menu directly with MapFlip.",
        val setupAltClipboard: String = "Clipboard: Copy a map link and open MapFlip for instant redirection.",
        val setupBtnOpenSettings: String = "Open system settings",
        val setupBtnDismiss: String = "Continue without setup",
        val setupStatusAllActive: String = "%d of %d links active",
        val setupStatusPartial: String = "%d of %d links active – tap to add more",
        val setupStatusNone: String = "No links active – setup required",
        val menuSetupGuide: String = "Setup Guide (Android 12+)"
    ) {
        fun formatStatusAllActive(count: Int): String {
            return try {
                setupStatusAllActive.format(count, count)
            } catch (_: Exception) {
                "$count of $count links active"
            }
        }

        fun formatStatusPartial(enabled: Int, total: Int): String {
            return try {
                setupStatusPartial.format(enabled, total)
            } catch (_: Exception) {
                "$enabled of $total links active"
            }
        }
        val effectivePrivacyNote: String
            get() = if (de.goork.mapflip.BuildConfig.FLAVOR == "play" && privacyNotePlay.isNotBlank()) privacyNotePlay else privacyNote

        fun testButtonLabel(targetApp: de.goork.mapflip.navigation.TargetNavigationApp): String {
            val appName = when (targetApp) {
                de.goork.mapflip.navigation.TargetNavigationApp.GOOGLE_MAPS -> "Google Maps"
                de.goork.mapflip.navigation.TargetNavigationApp.WAZE -> "Waze"
                de.goork.mapflip.navigation.TargetNavigationApp.ORGANIC_MAPS -> "Organic Maps"
                de.goork.mapflip.navigation.TargetNavigationApp.OSMAND -> "OsmAnd"
                de.goork.mapflip.navigation.TargetNavigationApp.HERE_WEGO -> "HERE WeGo"
                de.goork.mapflip.navigation.TargetNavigationApp.YANDEX_MAPS -> "Yandex Maps"
                de.goork.mapflip.navigation.TargetNavigationApp.MAGIC_EARTH -> "Magic Earth"
                de.goork.mapflip.navigation.TargetNavigationApp.CITYMAPPER -> "Citymapper"
                de.goork.mapflip.navigation.TargetNavigationApp.KOMOOT -> "Komoot"
                de.goork.mapflip.navigation.TargetNavigationApp.TOMTOM_AMIGO -> "TomTom AmiGO"
                de.goork.mapflip.navigation.TargetNavigationApp.SYGIC -> "Sygic"
                de.goork.mapflip.navigation.TargetNavigationApp.LOCUS_MAP -> "Locus Map"
                de.goork.mapflip.navigation.TargetNavigationApp.SYSTEM_PICKER -> if (sectionTargetApp.isNotBlank()) sectionTargetApp else "Navigation App"
            }
            return try {
                btnTestLink.format(appName)
            } catch (_: Exception) {
                "Test ($appName)"
            }
        }

        fun openInButtonLabel(targetApp: de.goork.mapflip.navigation.TargetNavigationApp): String {
            val appName = when (targetApp) {
                de.goork.mapflip.navigation.TargetNavigationApp.GOOGLE_MAPS -> "Google Maps"
                de.goork.mapflip.navigation.TargetNavigationApp.WAZE -> "Waze"
                de.goork.mapflip.navigation.TargetNavigationApp.ORGANIC_MAPS -> "Organic Maps"
                de.goork.mapflip.navigation.TargetNavigationApp.OSMAND -> "OsmAnd"
                de.goork.mapflip.navigation.TargetNavigationApp.HERE_WEGO -> "HERE WeGo"
                de.goork.mapflip.navigation.TargetNavigationApp.YANDEX_MAPS -> "Yandex Maps"
                de.goork.mapflip.navigation.TargetNavigationApp.MAGIC_EARTH -> "Magic Earth"
                de.goork.mapflip.navigation.TargetNavigationApp.CITYMAPPER -> "Citymapper"
                de.goork.mapflip.navigation.TargetNavigationApp.KOMOOT -> "Komoot"
                de.goork.mapflip.navigation.TargetNavigationApp.TOMTOM_AMIGO -> "TomTom AmiGO"
                de.goork.mapflip.navigation.TargetNavigationApp.SYGIC -> "Sygic"
                de.goork.mapflip.navigation.TargetNavigationApp.LOCUS_MAP -> "Locus Map"
                de.goork.mapflip.navigation.TargetNavigationApp.SYSTEM_PICKER -> if (sectionTargetApp.isNotBlank()) sectionTargetApp else "Navigation App"
            }
            return try {
                btnOpenInApp.format(appName)
            } catch (_: Exception) {
                "Open in $appName"
            }
        }

        fun appNotInstalledToast(appName: String): String {
            return try {
                appNotInstalled.format(appName)
            } catch (_: Exception) {
                "$appName is not installed"
            }
        }
    }

    fun resolveLanguage(savedPref: String?): String {
        if (!savedPref.isNullOrBlank() && savedPref != "auto") {
            return savedPref
        }
        val locale = Locale.getDefault()
        val lang = locale.language.lowercase()
        val country = locale.country.uppercase()
        if (lang == "zh") {
            return if (country == "TW" || country == "HK" || country == "MO") "zh-tw" else "zh"
        }
        return when (lang) {
            "de", "en", "da", "fr", "it", "ja", "nl", "no", "pl", "pt", "sv", "es", "tr", "ko", "ar", "ru", "id" -> lang
            else -> "en"
        }
    }

    fun getStrings(langCode: String): AppStrings {
        return when (langCode.lowercase()) {
            "de" -> DE
            "en" -> EN
            "da" -> DA
            "fr" -> FR
            "it" -> IT
            "ja" -> JA
            "nl" -> NL
            "no" -> NO
            "pl" -> PL
            "pt" -> PT
            "sv" -> SV
            "es" -> ES
            "tr" -> TR
            "ko" -> KO
            "zh" -> ZH_CN
            "zh-tw" -> ZH_TW
            "ar" -> AR
            "ru" -> RU
            "id" -> ID
            else -> EN
        }
    }

    val DE = AppStrings(
        headline = "MapFlip",
        subtitle = "Apple Maps \u2192 Google Maps",
        tagline = "Automatisch. Unsichtbar.",
        setupTitle = "So geht\u2019s",
        step1 = "Tippe auf den Button \"Einstellungen öffnen\"",
        step2 = "Aktiviere \"Unterst\u00fctzte Links \u00f6ffnen\" f\u00fcr die gew\u00fcnschten Kartendienste (z.B. Apple, Bing, OSM, Yandex)",
        step3 = "Fertig! Karten-Links \u00f6ffnen sich ab jetzt nahtlos in deiner bevorzugten Navigations-App.",
        btnSettings = "Einstellungen \u00f6ffnen",
        statusActive = "Links sind aktiviert",
        statusInactive = "Links sind noch nicht aktiv",
        statusHint = "Auf \u00e4lteren Android-Versionen kann der Status nicht gepr\u00fcft werden.",
        famwakeTitle = "FamWake \u2013 Familienwecker",
        famwakePromo = "Vom gleichen Entwickler",
        famwakeDesc = "FamWake koordiniert den Morgen f\u00fcr die ganze Familie \u2013 Bad-Zeiten, Fr\u00fchst\u00fcck und Aufstehen.",
        famwakeButton = "Mehr erfahren",
        copyright = "\u00a9 2026 Daniel Notthoff",
        langToggle = "DE",
        btnFeedback = "Support",
        pauseTitle = "Weiterleitung pausieren",
        pauseDesc = "Vorübergehend alle Umleitungen aussetzen",
        statusPaused = "Weiterleitung ist pausiert",
        selectLanguageTitle = "Sprache wählen",
        systemLanguageAuto = "Systemstandard (Automatisch)",
        btnRateApp = "App bewerten",
        privacyNote = "100% datenschutzfreundlich: Alle Konvertierungen finden lokal statt. Keine Datenerfassung.",
        privacyNotePlay = "100% datenschutzfreundlich: Alle Konvertierungen finden lokal statt. Keine Erfassung persönlicher Daten oder Standorte.",
        testLinkTitle = "Link-Tester & Zwischenablage",
        testLinkHint = "Karten-Link hier eingeben (Apple, Bing, OSM, Yandex)...",
        btnPasteClipboard = "Einfügen",
        btnTestLink = "In %s testen",
        testLinkConvertedLabel = "Umgewandelte Ziel-URI:",
        pauseIndefinitely = "Unbegrenzt",
        pause1Hour = "1 Stunde",
        pause8Hours = "8 Stunden",
        pauseUntilTomorrow = "Bis morgen früh",
        dialogPauseTitle = "Pausendauer wählen",
        menuSettingsAbout = "Einstellungen & Info",
        aboutTitle = "Über MapFlip",
        appVersionLabel = "Version",
        btnClose = "Schließen",
        sectionLanguage = "Sprache",
        sectionTheme = "Erscheinungsbild",
        themeSystem = "Systemstandard",
        themeLight = "Hell",
        themeDark = "Dunkel",
        btnDonate = "Spenden",
        donateSubtitle = "Unterstütze die Entwicklung auf Ko-fi",
        privacyPolicyTitle = "Datenschutzerklärung",
        impressumTitle = "Impressum",
        sectionGeneral = "Allgemein",
        sectionAbout = "Über die App",
        quickGuideTitle = "Kurzanleitung",
        sectionTargetApp = "Ziel-Navigations-App",
        targetAppAlwaysAsk = "Immer fragen (Systemauswahl)",
        btnCopyLink = "Link kopieren",
        linkCopiedToast = "Link in die Zwischenablage kopiert",
        btnShareLink = "Link teilen",
        btnClearInput = "Löschen",
        clipboardDetectedTitle = "Karten-Link in Zwischenablage",
        btnOpenInApp = "In %s öffnen",
        actionExpand = "Ausklappen",
        actionCollapse = "Einklappen",
        appNotInstalled = "%s ist nicht installiert",
        targetAppOpenError = "Ziel-App konnte nicht geöffnet werden",
        statusInstalled = "Installiert",
        statusNotInstalled = "Nicht installiert",
        tileSetupRequired = "Einrichtung erforderlich",
        targetAppFallbackOpened = "%s ist nicht installiert – mit %s geöffnet",
        redirectingToApp = "Weiterleiten an %s...",
        setupSheetTitle = "Karten-Links einrichten",
        setupSheetSubtitle = "Android 12+ erfordert die manuelle Bestätigung unterstützter Karten-Links.",
        setupStep1Title = "Einstellungen öffnen",
        setupStep1Desc = "Tippe unten auf den Button, um die Android-Einstellungen für MapFlip zu öffnen.",
        setupStep2Title = "\"Standardmäßig öffnen\" wählen",
        setupStep2Desc = "Tippe auf \"Unterstützte Links öffnen\" oder \"Links hinzufügen\".",
        setupStep3Title = "Karten-Links aktivieren",
        setupStep3Desc = "Hake alle gewünschten Kartendienste an (Apple, Bing, OSM, HERE etc.).",
        setupAltTitle = "Funktioniert sofort ohne Einrichtung:",
        setupAltShare = "Teilen-Menü: Teile einen Karten-Link über Androids Teilen-Menü direkt mit MapFlip.",
        setupAltClipboard = "Zwischenablage: Kopiere einen Karten-Link und öffne MapFlip für eine sofortige Weiterleitung.",
        setupBtnOpenSettings = "Systemeinstellungen öffnen",
        setupBtnDismiss = "Ohne Einrichtung fortfahren",
        setupStatusAllActive = "%d von %d Links aktiv",
        setupStatusPartial = "%d von %d Links aktiv – weitere hinzufügen",
        setupStatusNone = "Keine Links aktiv – Einrichtung erforderlich",
        menuSetupGuide = "Einrichtungs-Hilfe (Android 12+)",
    )

    val EN = AppStrings(
        headline = "MapFlip",
        subtitle = "Apple Maps \u2192 Google Maps",
        tagline = "Automatic. Invisible.",
        setupTitle = "How it works",
        step1 = "Tap the \"Open Settings\" button",
        step2 = "Enable \"Open supported links\" for the map services you want (e.g. Apple, Bing, OSM, Yandex)",
        step3 = "Done! Map links will now open seamlessly in your preferred navigation app.",
        btnSettings = "Open Settings",
        statusActive = "Links are enabled",
        statusInactive = "Links are not yet active",
        statusHint = "Status cannot be checked on older Android versions.",
        famwakeTitle = "FamWake \u2013 Family Alarm Clock",
        famwakePromo = "From the same developer",
        famwakeDesc = "FamWake coordinates the morning for the whole family \u2013 bathroom times, breakfast, and wake-up.",
        famwakeButton = "Learn more",
        copyright = "\u00a9 2026 Daniel Notthoff",
        langToggle = "EN",
        btnFeedback = "Support",
        pauseTitle = "Pause Redirect",
        pauseDesc = "Temporarily suspend all link redirects",
        statusPaused = "Redirect is paused",
        selectLanguageTitle = "Select Language",
        systemLanguageAuto = "System Default (Auto)",
        btnRateApp = "Rate App",
        privacyNote = "100% privacy-friendly: All redirects are processed locally. No data collection.",
        privacyNotePlay = "100% privacy-friendly: All redirects are processed locally. No personal data or location tracking.",
        testLinkTitle = "Link Tester & Clipboard",
        testLinkHint = "Enter map link here (Apple, Bing, OSM, Yandex)...",
        btnPasteClipboard = "Paste",
        btnTestLink = "Test in %s",
        testLinkConvertedLabel = "Converted Target URI:",
        pauseIndefinitely = "Indefinitely",
        pause1Hour = "1 Hour",
        pause8Hours = "8 Hours",
        pauseUntilTomorrow = "Until tomorrow morning",
        dialogPauseTitle = "Select Pause Duration",
        menuSettingsAbout = "Settings & About",
        aboutTitle = "About MapFlip",
        appVersionLabel = "Version",
        btnClose = "Close",
        sectionLanguage = "Language",
        sectionTheme = "Appearance",
        themeSystem = "System default",
        themeLight = "Light",
        themeDark = "Dark",
        btnDonate = "Donate",
        donateSubtitle = "Support the development on Ko-fi",
        privacyPolicyTitle = "Privacy Policy",
        impressumTitle = "Legal Notice (Impressum)",
        sectionGeneral = "General",
        sectionAbout = "About",
        quickGuideTitle = "Setup Guide",
        clipboardDetectedTitle = "Map link in clipboard",
        btnOpenInApp = "Open in %s",
        actionExpand = "Expand",
        actionCollapse = "Collapse",
        appNotInstalled = "%s is not installed",
        targetAppOpenError = "Target app could not be opened"
    )

    val DA = EN.copy(
        tagline = "Automatisk. Usynlig.",
        setupTitle = "Sådan virker det",
        step1 = "Tryk på knappen \"Åbn indstillinger\"",
        step2 = "Aktivér \"Åbn links\" for maps.apple.com",
        step3 = "Færdig! Apple Maps links åbnes nu automatisk i Google Maps.",
        btnSettings = "Åbn indstillinger",
        statusActive = "Links er aktiveret",
        statusInactive = "Links er endnu ikke aktive",
        statusHint = "Status kan ikke kontrolleres på ældre Android-versioner.",
        famwakeTitle = "FamWake – Familievækkeur",
        famwakePromo = "Fra samme udvikler",
        famwakeDesc = "FamWake koordinerer morgenen for hele familien – badeværelsestider, morgenmad og opvågning.",
        famwakeButton = "Læs mere",
        langToggle = "DA",
        btnFeedback = "Support",
        pauseTitle = "Pausér omdirigering",
        pauseDesc = "Midlertidigt afbryd alle linkomdirigeringer",
        statusPaused = "Omdirigering er sat på pause",
        selectLanguageTitle = "Vælg sprog",
        systemLanguageAuto = "Systemstandard (Automatisk)",
        btnRateApp = "Bedøm app",
        privacyNote = "100% privatlivsvenlig: Alle omdirigeringer sker lokalt. Ingen dataindsamling.",
        privacyNotePlay = "100% privatlivsvenlig: Alle omdirigeringer sker lokalt. Ingen sporing af personlige data eller placering.",
        testLinkTitle = "Link-tester & udklipsholder",
        testLinkHint = "Indtast Apple Maps-link her...",
        btnPasteClipboard = "Indsæt",
        btnTestLink = "Test i %s",
        testLinkConvertedLabel = "Konverteret mål-URI:",
        pauseIndefinitely = "Ubegrænset",
        pause1Hour = "1 time",
        pause8Hours = "8 timer",
        pauseUntilTomorrow = "Indtil i morgen tidlig",
        dialogPauseTitle = "Vælg pauseduration",
        menuSettingsAbout = "Indstillinger & Om",
        aboutTitle = "Om MapFlip",
        appVersionLabel = "Version",
        btnClose = "Luk",
        sectionLanguage = "Sprog",
        sectionTheme = "Udseende",
        themeSystem = "Systemstandard",
        themeLight = "Lyst",
        themeDark = "Mørkt",
        btnDonate = "Donér",
        donateSubtitle = "Støt udviklingen på Ko-fi",
        privacyPolicyTitle = "Privatlivspolitik",
        impressumTitle = "Kolofon (Impressum)",
        sectionGeneral = "Generelt",
        sectionAbout = "Om appen",
        quickGuideTitle = "Startguide",
        btnCopyLink = "Kopier link",
        linkCopiedToast = "Link kopieret til udklipsholder",
        btnShareLink = "Del link",
        btnClearInput = "Ryd",
        clipboardDetectedTitle = "Kortlink i udklipsholder",
        btnOpenInApp = "Åbn i %s",
        actionExpand = "Fold ud",
        actionCollapse = "Fold sammen",
        appNotInstalled = "%s er ikke installeret",
        targetAppOpenError = "Destinationsapp kunne ikke åbnes",
        statusInstalled = "Installeret",
        statusNotInstalled = "Ikke installeret",
        tileSetupRequired = "Opsætning påkrævet",
        setupSheetTitle = "Konfigurer kortlinks",
        setupSheetSubtitle = "Android 12+ kræver manuel bekræftelse af understøttede kortlinks.",
        setupStep1Title = "Åbn systemindstillinger",
        setupStep1Desc = "Tryk på knappen nedenfor for at åbne MapFlips indstillinger.",
        setupStep2Title = "Vælg \"Åbn som standard\"",
        setupStep2Desc = "Tryk på \"Åbn understøttede links\" eller \"Tilføj links\".",
        setupStep3Title = "Aktivér kortlinks",
        setupStep3Desc = "Marker alle understøttede korttjenester (Apple, Bing, OSM, HERE osv.).",
        setupAltTitle = "Virker med det samme uden opsætning:",
        setupAltShare = "Delemenu: Del et kortlink via Androids delemenu direkte med MapFlip.",
        setupAltClipboard = "Udklipsholder: Kopiér et kortlink og åbn MapFlip for øjeblikkelig omdirigering.",
        setupBtnOpenSettings = "Åbn systemindstillinger",
        setupBtnDismiss = "Fortsæt uden opsætning",
        setupStatusAllActive = "%d af %d links aktive",
        setupStatusPartial = "%d af %d links aktive – tryk for at tilføje flere",
        setupStatusNone = "Ingen links aktive – opsætning påkrævet",
        menuSetupGuide = "Opsætningsvejledning (Android 12+)",
    )

    val FR = EN.copy(
        tagline = "Automatique. Invisible.",
        setupTitle = "Comment ça marche",
        step1 = "Appuyez sur le bouton \"Ouvrir les paramètres\"",
        step2 = "Activez \"Ouvrir les liens\" pour maps.apple.com",
        step3 = "Terminé! Les liens Apple Maps s'ouvriront désormais automatiquement dans Google Maps.",
        btnSettings = "Ouvrir les paramètres",
        statusActive = "Les liens sont activés",
        statusInactive = "Les liens ne sont pas encore actifs",
        statusHint = "Le statut ne peut pas être vérifié sur les anciennes versions d'Android.",
        famwakeTitle = "FamWake – Réveil Familial",
        famwakePromo = "Du même développeur",
        famwakeDesc = "FamWake coordonne le matin pour toute la famille – temps de salle de bain, petit-déjeuner et réveil.",
        famwakeButton = "En savoir plus",
        langToggle = "FR",
        btnFeedback = "Support",
        pauseTitle = "Mettre en pause la redirection",
        pauseDesc = "Suspendre temporairement toutes les redirections",
        statusPaused = "La redirection est en pause",
        selectLanguageTitle = "Choisir la langue",
        systemLanguageAuto = "Par défaut du système (Auto)",
        btnRateApp = "Évaluer l'application",
        privacyNote = "100% respectueux de la vie privée : redirection locale, aucune collecte de données.",
        privacyNotePlay = "100% respectueux de la vie privée : redirection locale. Aucune donnée personnelle ni localisation collectée.",
        testLinkTitle = "Testeur de liens & presse-papiers",
        testLinkHint = "Entrez le lien Apple Maps ici...",
        btnPasteClipboard = "Coller",
        btnTestLink = "Tester dans %s",
        testLinkConvertedLabel = "URI cible convertie :",
        pauseIndefinitely = "Indéfiniment",
        pause1Hour = "1 heure",
        pause8Hours = "8 heures",
        pauseUntilTomorrow = "Jusqu'à demain matin",
        dialogPauseTitle = "Sélectionner la durée de pause",
        menuSettingsAbout = "Paramètres & À propos",
        aboutTitle = "À propos de MapFlip",
        appVersionLabel = "Version",
        btnClose = "Fermer",
        sectionLanguage = "Langue",
        sectionTheme = "Apparence",
        themeSystem = "Par défaut du système",
        themeLight = "Clair",
        themeDark = "Sombre",
        btnDonate = "Faire un don",
        donateSubtitle = "Soutenir le développement sur Ko-fi",
        privacyPolicyTitle = "Politique de confidentialité",
        impressumTitle = "Mentions Légales (Impressum)",
        sectionGeneral = "Général",
        sectionAbout = "À propos de l'application",
        quickGuideTitle = "Guide de configuration",
        btnCopyLink = "Copier le lien",
        linkCopiedToast = "Lien copié dans le presse-papiers",
        btnShareLink = "Partager le lien",
        btnClearInput = "Effacer",
        clipboardDetectedTitle = "Lien de carte dans le presse-papiers",
        btnOpenInApp = "Ouvrir dans %s",
        actionExpand = "Développer",
        actionCollapse = "Réduire",
        appNotInstalled = "%s n'est pas installée",
        targetAppOpenError = "Impossible d'ouvrir l'application cible",
        statusInstalled = "Installée",
        statusNotInstalled = "Non installée",
        tileSetupRequired = "Configuration requise",
        setupSheetTitle = "Configurer les liens de carte",
        setupSheetSubtitle = "Android 12+ requiert la confirmation manuelle des liens de carte pris en charge.",
        setupStep1Title = "Ouvrir les paramètres système",
        setupStep1Desc = "Appuyez sur le bouton ci-dessous pour ouvrir les paramètres de MapFlip.",
        setupStep2Title = "Sélectionner \"Ouvrir par défaut\"",
        setupStep2Desc = "Appuyez sur \"Ouvrir les liens pris en charge\" ou \"Ajouter un lien\".",
        setupStep3Title = "Activer les liens de carte",
        setupStep3Desc = "Cochez tous les services de carte souhaités (Apple, Bing, OSM, HERE, etc.).",
        setupAltTitle = "Fonctionne immédiatement sans configuration :",
        setupAltShare = "Menu Partager : Partagez n'importe quel lien de carte via le menu Partager d'Android directement avec MapFlip.",
        setupAltClipboard = "Presse-papiers : Copiez un lien de carte et ouvrez MapFlip pour une redirection immédiate.",
        setupBtnOpenSettings = "Ouvrir les paramètres système",
        setupBtnDismiss = "Continuer sans configurer",
        setupStatusAllActive = "%d sur %d liens actifs",
        setupStatusPartial = "%d sur %d liens actifs – appuyez pour en ajouter",
        setupStatusNone = "Aucun lien actif – configuration requise",
        menuSetupGuide = "Guide de configuration (Android 12+)",
    )

    val IT = EN.copy(
        tagline = "Automatico. Invisibile.",
        setupTitle = "Come funziona",
        step1 = "Tocca il pulsante \"Apri Impostazioni\"",
        step2 = "Attiva \"Apri link\" per maps.apple.com",
        step3 = "Fatto! I link di Apple Maps si apriranno ora automaticamente in Google Maps.",
        btnSettings = "Apri Impostazioni",
        statusActive = "I link sono attivi",
        statusInactive = "I link non sono ancora attivi",
        statusHint = "Lo stato non può essere verificato sulle versioni Android meno recenti.",
        famwakeTitle = "FamWake – Sveglia per la Famiglia",
        famwakePromo = "Dallo stesso sviluppatore",
        famwakeDesc = "FamWake coordina il risveglio per tutta la famiglia – turni per il bagno, colazione e sveglia.",
        famwakeButton = "Scopri di più",
        langToggle = "IT",
        btnFeedback = "Supporto",
        pauseTitle = "Pausa reindirizzamento",
        pauseDesc = "Sospendi temporaneamente tutti i reindirizzamenti",
        statusPaused = "Il reindirizzamento è in pausa",
        selectLanguageTitle = "Seleziona lingua",
        systemLanguageAuto = "Predefinita di sistema (Auto)",
        btnRateApp = "Valuta l'app",
        privacyNote = "100% rispetto della privacy: il reindirizzamento avviene localmente. Nessuna raccolta dati.",
        privacyNotePlay = "100% rispetto della privacy: il reindirizzamento avviene localmente. Nessun dato personale o posizione tracciata.",
        testLinkTitle = "Tester di link e appunti",
        testLinkHint = "Inserisci qui il link di Apple Maps...",
        btnPasteClipboard = "Incolla",
        btnTestLink = "Testa in %s",
        testLinkConvertedLabel = "URI di destinazione convertito:",
        pauseIndefinitely = "A tempo indeterminato",
        pause1Hour = "1 ora",
        pause8Hours = "8 ore",
        pauseUntilTomorrow = "Fino a domani mattina",
        dialogPauseTitle = "Seleziona durata pausa",
        menuSettingsAbout = "Impostazioni e Informazioni",
        aboutTitle = "Informazioni su MapFlip",
        appVersionLabel = "Version",
        btnClose = "Chiudi",
        sectionLanguage = "Lingua",
        sectionTheme = "Aspetto",
        themeSystem = "Predefinito di sistema",
        themeLight = "Chiaro",
        themeDark = "Scuro",
        btnDonate = "Donazione",
        donateSubtitle = "Sostieni lo sviluppo su Ko-fi",
        privacyPolicyTitle = "Informativa sulla privacy",
        impressumTitle = "Note Legali (Impressum)",
        sectionGeneral = "Generale",
        sectionAbout = "Informazioni sull'app",
        quickGuideTitle = "Guida introduttiva",
        btnCopyLink = "Copia link",
        linkCopiedToast = "Link copiato negli appunti",
        btnShareLink = "Condividi link",
        btnClearInput = "Cancella",
        clipboardDetectedTitle = "Link mappa negli appunti",
        btnOpenInApp = "Apri in %s",
        actionExpand = "Espandi",
        actionCollapse = "Comprimi",
        appNotInstalled = "%s non è installata",
        targetAppOpenError = "Impossibile aprire l'app di destinazione",
        statusInstalled = "Installata",
        statusNotInstalled = "Non installata",
        tileSetupRequired = "Configurazione richiesta",
        setupSheetTitle = "Configura i link delle mappe",
        setupSheetSubtitle = "Android 12+ richiede la conferma manuale dei link supportati.",
        setupStep1Title = "Apri impostazioni di sistema",
        setupStep1Desc = "Tocca il pulsante qui sotto per aprire le impostazioni di MapFlip.",
        setupStep2Title = "Seleziona \"Apri per impostazione predefinita\"",
        setupStep2Desc = "Tocca \"Apri link supportati\" o \"Aggiungi link\".",
        setupStep3Title = "Attiva i domini delle mappe",
        setupStep3Desc = "Spunta tutti i servizi supportati (Apple, Bing, OSM, HERE ecc.).",
        setupAltTitle = "Funziona subito senza configurazione:",
        setupAltShare = "Menu Condividi: Condividi qualsiasi link di mappa tramite il menu Condividi di Android direttamente con MapFlip.",
        setupAltClipboard = "Appunti: Copia un link di mappa e apri MapFlip per il reindirizzamento immediato.",
        setupBtnOpenSettings = "Apri impostazioni di sistema",
        setupBtnDismiss = "Continua senza configurazione",
        setupStatusAllActive = "%d su %d link attivi",
        setupStatusPartial = "%d su %d link attivi – tocca per aggiungerne altri",
        setupStatusNone = "Nessun link attivo – configurazione richiesta",
        menuSetupGuide = "Guida configurazione (Android 12+)",
    )

    val JA = EN.copy(
        tagline = "自動。バックグラウンド。",
        setupTitle = "使い方",
        step1 = "「設定を開く」ボタンをタップ",
        step2 = "maps.apple.com の「リンクを開く」を有効化",
        step3 = "完了！Apple Maps のリンクが Google Maps で自動的に開きます。",
        btnSettings = "設定を開く",
        statusActive = "リンク機能は有効です",
        statusInactive = "リンク機能はまだ有効ではありません",
        statusHint = "古い Android バージョンではステータスを確認できません。",
        famwakeTitle = "FamWake – 家族用目覚まし",
        famwakePromo = "同じ開発者によるアプリ",
        famwakeDesc = "FamWakeは家族全員の朝をコーディネート – 洗面所の順番、朝食、起床時間をスマートに管理。",
        famwakeButton = "詳しく見る",
        langToggle = "JA",
        btnFeedback = "サポート",
        pauseTitle = "転送を一時停止",
        pauseDesc = "すべてのリンク転送を一時的に停止します",
        statusPaused = "転送は一時停止中です",
        selectLanguageTitle = "言語を選択",
        systemLanguageAuto = "システムデフォルト (自動)",
        btnRateApp = "アプリを評価する",
        privacyNote = "100% プライバシー保護：転送処理はすべてローカルで行われ、データ収集は一切行いません。",
        privacyNotePlay = "100% プライバシー保護：転送処理はすべてローカルで行われ、個人情報や位置情報は収集しません。",
        testLinkTitle = "リンクテスター＆クリップボード",
        testLinkHint = "Apple Mapsリンクをここに入力...",
        btnPasteClipboard = "貼り付け",
        btnTestLink = "%sでテスト",
        testLinkConvertedLabel = "変換されたターゲットURI:",
        pauseIndefinitely = "無制限",
        pause1Hour = "1時間",
        pause8Hours = "8時間",
        pauseUntilTomorrow = "明日の朝まで",
        dialogPauseTitle = "一時停止期間を選択",
        menuSettingsAbout = "設定と情報",
        aboutTitle = "MapFlipについて",
        appVersionLabel = "バージョン",
        btnClose = "閉じる",
        sectionLanguage = "言語",
        sectionTheme = "テーマ",
        themeSystem = "システムデフォルト",
        themeLight = "ライト",
        themeDark = "ダーク",
        btnDonate = "寄付する",
        donateSubtitle = "Ko-fiで開発をサポート",
        privacyPolicyTitle = "プライバシーポリシー",
        impressumTitle = "運営者情報 (Impressum)",
        sectionGeneral = "一般",
        sectionAbout = "アプリについて",
        quickGuideTitle = "クイックガイド",
        btnCopyLink = "リンクをコピー",
        linkCopiedToast = "リンクをクリップボードにコピーしました",
        btnShareLink = "リンクを共有",
        btnClearInput = "クリア",
        clipboardDetectedTitle = "クリップボードのマップリンク",
        btnOpenInApp = "%sで開く",
        actionExpand = "展開",
        actionCollapse = "折りたたむ",
        appNotInstalled = "%sがインストールされていません",
        targetAppOpenError = "対象アプリを開けませんでした",
        statusInstalled = "インストール済み",
        statusNotInstalled = "未インストール",
        tileSetupRequired = "設定が必要です",
        setupSheetTitle = "マップリンクの設定",
        setupSheetSubtitle = "Android 12以降では、対応する地図リンクを手動で許可する必要があります。",
        setupStep1Title = "システム設定を開く",
        setupStep1Desc = "下のボタンをタップしてMapFlipの設定画面を開きます。",
        setupStep2Title = "「デフォルトで開く」を選択",
        setupStep2Desc = "「対応リンクを開く」または「リンクを追加」をタップします。",
        setupStep3Title = "地図リンクを有効化",
        setupStep3Desc = "対応するすべての地図サービス（Apple、Bing、OSM、HEREなど）にチェックを入れます。",
        setupAltTitle = "設定不要ですぐに利用する方法:",
        setupAltShare = "共有メニュー: 地図リンクをAndroidの共有メニューから直接MapFlipと共有します。",
        setupAltClipboard = "クリップボード: 地図リンクをコピーしてMapFlipを開くと、自動で転送されます。",
        setupBtnOpenSettings = "システム設定を開く",
        setupBtnDismiss = "設定せずに続ける",
        setupStatusAllActive = "%d / %d 個のリンクが有効",
        setupStatusPartial = "%d / %d 個のリンクが有効 – タップして追加",
        setupStatusNone = "リンクが無効です – 設定が必要です",
        menuSetupGuide = "設定ガイド (Android 12+)",
    )

    val NL = EN.copy(
        tagline = "Automatisch. Onzichtbaar.",
        setupTitle = "Hoe het werkt",
        step1 = "Tik op de knop \"Instellingen openen\"",
        step2 = "Schakel \"Links openen\" in voor maps.apple.com",
        step3 = "Klaar! Apple Maps-links openen vanaf nu automatisch in Google Maps.",
        btnSettings = "Instellingen openen",
        statusActive = "Links zijn ingeschakeld",
        statusInactive = "Links zijn nog niet actief",
        statusHint = "Status kan niet worden gecontroleerd op oudere Android-versies.",
        famwakeTitle = "FamWake – Familiewekker",
        famwakePromo = "Van dezelfde ontwikkelaar",
        famwakeDesc = "FamWake coördineert de ochtend voor het hele gezin – badkamertijden, ontbijt en opstaan.",
        famwakeButton = "Meer ontdekken",
        langToggle = "NL",
        btnFeedback = "Support",
        pauseTitle = "Omleiding pauzeren",
        pauseDesc = "Tijdelijk alle link-omleidingen onderbreken",
        statusPaused = "Omleiding is gepauzeerd",
        selectLanguageTitle = "Taal selecteren",
        systemLanguageAuto = "Systeemstandaard (Automatisch)",
        btnRateApp = "Beoordeel app",
        privacyNote = "100% privacyvriendelijk: alle omleidingen vinden lokaal plaats. Geen gegevensverzameling.",
        privacyNotePlay = "100% privacyvriendelijk: alle omleidingen vinden lokaal plaats. Geen persoonlijke gegevens of locatieverzameling.",
        testLinkTitle = "Link-tester & klembord",
        testLinkHint = "Voer hier Apple Maps-link in...",
        btnPasteClipboard = "Plakken",
        btnTestLink = "Testen in %s",
        testLinkConvertedLabel = "Geconverteerde doel-URI:",
        pauseIndefinitely = "Onbeperkt",
        pause1Hour = "1 uur",
        pause8Hours = "8 uur",
        pauseUntilTomorrow = "Tot morgenochtend",
        dialogPauseTitle = "Pauzeduur selecteren",
        menuSettingsAbout = "Instellingen & Over",
        aboutTitle = "Over MapFlip",
        appVersionLabel = "Versie",
        btnClose = "Sluiten",
        sectionLanguage = "Taal",
        sectionTheme = "Weergave",
        themeSystem = "Systeemstandaard",
        themeLight = "Licht",
        themeDark = "Donker",
        btnDonate = "Doneren",
        donateSubtitle = "Ondersteun de ontwikkeling op Ko-fi",
        privacyPolicyTitle = "Privacybeleid",
        impressumTitle = "Colofon (Impressum)",
        sectionGeneral = "Algemeen",
        sectionAbout = "Over de app",
        quickGuideTitle = "Snelstartgids",
        btnCopyLink = "Link kopiëren",
        linkCopiedToast = "Link gekopieerd naar klembord",
        btnShareLink = "Link delen",
        btnClearInput = "Wissen",
        clipboardDetectedTitle = "Kaartlink op klembord",
        btnOpenInApp = "Openen in %s",
        actionExpand = "Uitklappen",
        actionCollapse = "Inklappen",
        appNotInstalled = "%s is niet geïnstalleerd",
        targetAppOpenError = "Doel-app kon niet worden geopend",
        statusInstalled = "Geïnstalleerd",
        statusNotInstalled = "Niet geïnstalleerd",
        tileSetupRequired = "Installatie vereist",
        setupSheetTitle = "Kaartlinks instellen",
        setupSheetSubtitle = "Android 12+ vereist handmatige bevestiging van ondersteunde kaartlinks.",
        setupStep1Title = "Systeeminstellingen openen",
        setupStep1Desc = "Tik op de onderstaande knop om de MapFlip-instellingen te openen.",
        setupStep2Title = "Kies \"Standaard openen\"",
        setupStep2Desc = "Tik op \"Ondersteunde links openen\" of \"Links toevoegen\".",
        setupStep3Title = "Kaartlinks inschakelen",
        setupStep3Desc = "Vink alle gewenste kaartdiensten aan (Apple, Bing, OSM, HERE enz.).",
        setupAltTitle = "Werkt direct zonder configuratie:",
        setupAltShare = "Deelmenu: Deel een kaartlink via het Android-deelmenu rechtstreeks met MapFlip.",
        setupAltClipboard = "Klembord: Kopieer een kaartlink en open MapFlip voor directe doorverwijzing.",
        setupBtnOpenSettings = "Systeeminstellingen openen",
        setupBtnDismiss = "Doorgaan zonder instellen",
        setupStatusAllActive = "%d van %d links actief",
        setupStatusPartial = "%d van %d links actief – tik om meer toe te voegen",
        setupStatusNone = "Geen links actief – installatie vereist",
        menuSetupGuide = "Installatiehandleiding (Android 12+)",
    )

    val NO = EN.copy(
        tagline = "Automatisk. Usynlig.",
        setupTitle = "Slik fungerer det",
        step1 = "Trykk på knappen \"Åpne innstillinger\"",
        step2 = "Aktiver \"Åpne lenker\" for maps.apple.com",
        step3 = "Ferdig! Apple Maps-lenker åpnes nå automatisk i Google Maps.",
        btnSettings = "Åpne innstillinger",
        statusActive = "Lenker er aktivert",
        statusInactive = "Lenker er ikke aktive ennå",
        statusHint = "Status kan ikke sjekkes på eldre Android-versjoner.",
        famwakeTitle = "FamWake – Familiealarm",
        famwakePromo = "Fra samme utvikler",
        famwakeDesc = "FamWake koordinerer morgenen for hele familien – baderomstider, frokost og oppvåkning.",
        famwakeButton = "Finn ut mer",
        langToggle = "NO",
        btnFeedback = "Støtte",
        pauseTitle = "Sett viderekobling på pause",
        pauseDesc = "Avbryt midlertidig alle lenke-viderekoblinger",
        statusPaused = "Viderekobling er satt på pause",
        selectLanguageTitle = "Velg språk",
        systemLanguageAuto = "Systemstandard (Automatisk)",
        btnRateApp = "Vurder appen",
        privacyNote = "100% personvernvennlig: Alle viderekoblinger skjer lokalt. Ingen dataindsamling.",
        privacyNotePlay = "100% personvernvennlig: Alle viderekoblinger skjer lokalt. Ingen sporing av personopplysninger eller posisjon.",
        testLinkTitle = "Lenketester & utklippstavle",
        testLinkHint = "Skriv inn Apple Maps-lenke her...",
        btnPasteClipboard = "Lim inn",
        btnTestLink = "Test i %s",
        testLinkConvertedLabel = "Konvertert mål-URI:",
        pauseIndefinitely = "Ubegrenset",
        pause1Hour = "1 time",
        pause8Hours = "8 timer",
        pauseUntilTomorrow = "Til i morgen tidlig",
        dialogPauseTitle = "Velg pausedurasjon",
        menuSettingsAbout = "Innstillinger og info",
        aboutTitle = "Om MapFlip",
        appVersionLabel = "Versjon",
        btnClose = "Lukk",
        sectionLanguage = "Språk",
        sectionTheme = "Utseende",
        themeSystem = "Systemstandard",
        themeLight = "Lyst",
        themeDark = "Mørkt",
        btnDonate = "Doner",
        donateSubtitle = "Støtt utviklingen på Ko-fi",
        privacyPolicyTitle = "Personvernerklæring",
        impressumTitle = "Juridisk informasjon (Impressum)",
        sectionGeneral = "Generelt",
        sectionAbout = "Om appen",
        quickGuideTitle = "Hurtigveiledning",
        btnCopyLink = "Kopier lenke",
        linkCopiedToast = "Lenke kopiert til utklippstavlen",
        btnShareLink = "Del lenke",
        btnClearInput = "Tøm",
        clipboardDetectedTitle = "Kartlenke i utklippstavlen",
        btnOpenInApp = "Åpne i %s",
        actionExpand = "Vis mer",
        actionCollapse = "Vis mindre",
        appNotInstalled = "%s er ikke installert",
        targetAppOpenError = "Målappen kunne ikke åpnes",
        statusInstalled = "Installert",
        statusNotInstalled = "Ikke installert",
        tileSetupRequired = "Oppsett kreves",
        setupSheetTitle = "Konfigurer kartlenker",
        setupSheetSubtitle = "Android 12+ krever manuell bekreftelse av støttede kartlenker.",
        setupStep1Title = "Åpne systeminnstillinger",
        setupStep1Desc = "Trykk på knappen nedenfor for å åpne MapFlips innstillinger.",
        setupStep2Title = "Velg \"Åpne som standard\"",
        setupStep2Desc = "Trykk på \"Åpne støttede lenker\" eller \"Legg til lenker\".",
        setupStep3Title = "Aktiver kartlenker",
        setupStep3Desc = "Kryss av for alle støttede karttjenester (Apple, Bing, OSM, HERE osv.).",
        setupAltTitle = "Fungerer umiddelbart uten oppsett:",
        setupAltShare = "Delemeny: Del en kartlenke via Androids delemeny direkte med MapFlip.",
        setupAltClipboard = "Utklippstavle: Kopier en kartlenke og åpne MapFlip for umiddelbar omdirigering.",
        setupBtnOpenSettings = "Åpne systeminnstillinger",
        setupBtnDismiss = "Fortsett uten oppsett",
        setupStatusAllActive = "%d av %d lenker aktive",
        setupStatusPartial = "%d av %d lenker aktive – trykk for å legge til flere",
        setupStatusNone = "Ingen lenker aktive – oppsett kreves",
        menuSetupGuide = "Oppsettveiledning (Android 12+)",
    )

    val PL = EN.copy(
        tagline = "Automatycznie. Niewidocznie.",
        setupTitle = "Jak to działa",
        step1 = "Dotknij przycisku \"Otwórz ustawienia\"",
        step2 = "Włącz \"Otwieraj linki\" dla maps.apple.com",
        step3 = "Gotowe! Linki Apple Maps będą teraz automatycznie otwierać się w Google Maps.",
        btnSettings = "Otwórz ustawienia",
        statusActive = "Linki są włączone",
        statusInactive = "Linki nie są jeszcze aktywne",
        statusHint = "Nie można sprawdzić stanu na starszych wersjach systemu Android.",
        famwakeTitle = "FamWake – Budzik Rodzinny",
        famwakePromo = "Od tego samego twórcy",
        famwakeDesc = "FamWake koordynuje poranki dla całej rodziny – kolejka do łazienki, śniadanie i pobudka.",
        famwakeButton = "Dowiedz się więcej",
        langToggle = "PL",
        btnFeedback = "Pomoc",
        pauseTitle = "Wstrzymaj przekierowanie",
        pauseDesc = "Tymczasowo zawieś wszystkie przekierowania",
        statusPaused = "Przekierowanie jest wstrzymane",
        selectLanguageTitle = "Wybierz język",
        systemLanguageAuto = "Domyślny systemu (Auto)",
        btnRateApp = "Oceń aplikację",
        privacyNote = "100% prywatności: wszystkie przekierowania odbywają się lokalnie. Brak zbierania danych.",
        privacyNotePlay = "100% prywatności: wszystkie przekierowania odbywają się lokalnie. Brak gromadzenia danych osobowych i lokalizacji.",
        testLinkTitle = "Tester linków i schowek",
        testLinkHint = "Wpisz tutaj link Apple Maps...",
        btnPasteClipboard = "Wklej",
        btnTestLink = "Testuj w %s",
        testLinkConvertedLabel = "Przekonwertowany URI docelowy:",
        pauseIndefinitely = "Na czas nieokreślony",
        pause1Hour = "1 godzina",
        pause8Hours = "8 godzin",
        pauseUntilTomorrow = "Do jutra rano",
        dialogPauseTitle = "Wybierz czas wstrzymania",
        menuSettingsAbout = "Ustawienia i informacje",
        aboutTitle = "O aplikacji MapFlip",
        appVersionLabel = "Wersja",
        btnClose = "Zamknij",
        sectionLanguage = "Język",
        sectionTheme = "Wygląd",
        themeSystem = "Domyślny systemu",
        themeLight = "Jasny",
        themeDark = "Ciemny",
        btnDonate = "Wesprzyj",
        donateSubtitle = "Wesprzyj rozwój na Ko-fi",
        privacyPolicyTitle = "Polityka prywatności",
        impressumTitle = "Informacje prawne (Impressum)",
        sectionGeneral = "Ogólne",
        sectionAbout = "O aplikacji",
        quickGuideTitle = "Szybki przewodnik",
        btnCopyLink = "Kopiuj link",
        linkCopiedToast = "Link skopiowany do schowka",
        btnShareLink = "Udostępnij link",
        btnClearInput = "Wyczyść",
        clipboardDetectedTitle = "Link do mapy w schowku",
        btnOpenInApp = "Otwórz w %s",
        actionExpand = "Rozwiń",
        actionCollapse = "Zwiń",
        appNotInstalled = "Aplikacja %s nie jest zainstalowana",
        targetAppOpenError = "Nie udało się otworzyć aplikacji docelowej",
        statusInstalled = "Zainstalowano",
        statusNotInstalled = "Nie zainstalowano",
        tileSetupRequired = "Wymaga konfiguracji",
        setupSheetTitle = "Skonfiguruj linki map",
        setupSheetSubtitle = "Android 12+ wymaga ręcznego zatwierdzenia obsługiwanych linków map.",
        setupStep1Title = "Otwórz ustawienia systemowe",
        setupStep1Desc = "Dotknij poniższego przycisku, aby otworzyć ustawienia MapFlip.",
        setupStep2Title = "Wybierz \"Otwieraj domyślnie\"",
        setupStep2Desc = "Dotknij \"Otwieraj obsługiwane linki\" lub \"Dodaj linki\".",
        setupStep3Title = "Włącz linki map",
        setupStep3Desc = "Zaznacz wszystkie obsługiwane domeny map (Apple, Bing, OSM, HERE itp.).",
        setupAltTitle = "Działa natychmiast bez konfiguracji:",
        setupAltShare = "Menu Udostępnij: Udostępnij dowolny link mapy przez menu Udostępnij Androida bezpośrednio do MapFlip.",
        setupAltClipboard = "Schowek: Skopiuj link mapy i otwórz MapFlip w celu natychmiastowego przekierowania.",
        setupBtnOpenSettings = "Otwórz ustawienia systemowe",
        setupBtnDismiss = "Kontynuuj bez konfiguracji",
        setupStatusAllActive = "%d z %d linków aktywnych",
        setupStatusPartial = "%d z %d linków aktywnych – dotknij, aby dodać więcej",
        setupStatusNone = "Brak aktywnych linków – wymagana konfiguracja",
        menuSetupGuide = "Przewodnik konfiguracji (Android 12+)",
    )

    val PT = EN.copy(
        tagline = "Automático. Invisível.",
        setupTitle = "Como funciona",
        step1 = "Toque no botão \"Abrir Configurações\"",
        step2 = "Ative \"Abrir links\" para maps.apple.com",
        step3 = "Concluído! Os links do Apple Maps serão abertos automaticamente no Google Maps.",
        btnSettings = "Abrir Configurações",
        statusActive = "Links estão ativados",
        statusInactive = "Links ainda não estão ativos",
        statusHint = "O status não pode ser verificado em versões anteriores do Android.",
        famwakeTitle = "FamWake – Despertador Familiar",
        famwakePromo = "Do mesmo desenvolvedor",
        famwakeDesc = "O FamWake coordena as manhãs de toda a família – horários de casa de banho, pequeno-almoço e acordar.",
        famwakeButton = "Saber mais",
        langToggle = "PT",
        btnFeedback = "Suporte",
        pauseTitle = "Pausar redirecionamento",
        pauseDesc = "Suspender temporariamente todos os redirecionamentos",
        statusPaused = "O redirecionamento está pausado",
        selectLanguageTitle = "Selecionar idioma",
        systemLanguageAuto = "Padrão do sistema (Auto)",
        btnRateApp = "Avaliar app",
        privacyNote = "100% privacidade: todos os redirecionamentos ocorrem localmente. Sem coleta de dados.",
        privacyNotePlay = "100% privacidade: todos os redirecionamentos ocorrem localmente. Sem rastreamento de dados pessoais ou localização.",
        testLinkTitle = "Testador de links e área de transferência",
        testLinkHint = "Digite o link do Apple Maps aqui...",
        btnPasteClipboard = "Colar",
        btnTestLink = "Testar no %s",
        testLinkConvertedLabel = "URI de destino convertido:",
        pauseIndefinitely = "Indefinidamente",
        pause1Hour = "1 hora",
        pause8Hours = "8 horas",
        pauseUntilTomorrow = "Até amanhã de manhã",
        dialogPauseTitle = "Selecionar duração da pausa",
        menuSettingsAbout = "Configurações e Sobre",
        aboutTitle = "Sobre o MapFlip",
        appVersionLabel = "Versão",
        btnClose = "Fechar",
        sectionLanguage = "Idioma",
        sectionTheme = "Aparência",
        themeSystem = "Padrão do sistema",
        themeLight = "Claro",
        themeDark = "Escuro",
        btnDonate = "Doar",
        donateSubtitle = "Apoie o desenvolvimento no Ko-fi",
        privacyPolicyTitle = "Política de Privacidade",
        impressumTitle = "Aviso Legal (Impressum)",
        sectionGeneral = "Geral",
        sectionAbout = "Sobre a aplicação",
        quickGuideTitle = "Guia rápido",
        btnCopyLink = "Copiar link",
        linkCopiedToast = "Link copiado para a área de transferência",
        btnShareLink = "Compartilhar link",
        btnClearInput = "Limpar",
        clipboardDetectedTitle = "Link de mapa na área de transferência",
        btnOpenInApp = "Abrir no %s",
        actionExpand = "Expandir",
        actionCollapse = "Recolher",
        appNotInstalled = "%s não está instalado",
        targetAppOpenError = "Não foi possível abrir o app de destino",
        statusInstalled = "Instalado",
        statusNotInstalled = "Não instalado",
        tileSetupRequired = "Configuração necessária",
        setupSheetTitle = "Configurar links de mapas",
        setupSheetSubtitle = "O Android 12+ exige confirmação manual dos links de mapas compatíveis.",
        setupStep1Title = "Abrir configurações do sistema",
        setupStep1Desc = "Toque no botão abaixo para abrir as configurações do MapFlip.",
        setupStep2Title = "Selecione \"Abrir por padrão\"",
        setupStep2Desc = "Toque em \"Abrir links compatíveis\" ou \"Adicionar links\".",
        setupStep3Title = "Ativar links de mapas",
        setupStep3Desc = "Marque todos os domínios de mapas suportados (Apple, Bing, OSM, HERE etc.).",
        setupAltTitle = "Funciona instantaneamente sem configuração:",
        setupAltShare = "Menu Compartilhar: Compartilhe qualquer link de mapa pelo menu Compartilhar do Android diretamente com o MapFlip.",
        setupAltClipboard = "Área de transferência: Copie um link de mapa e abra o MapFlip para redirecionamento imediato.",
        setupBtnOpenSettings = "Abrir configurações do sistema",
        setupBtnDismiss = "Continuar sem configurar",
        setupStatusAllActive = "%d de %d links ativos",
        setupStatusPartial = "%d de %d links ativos – toque para adicionar mais",
        setupStatusNone = "Nenhum link ativo – configuração necessária",
        menuSetupGuide = "Guia de configuração (Android 12+)",
    )

    val SV = EN.copy(
        tagline = "Automatiskt. Osynligt.",
        setupTitle = "Hur det fungerar",
        step1 = "Tryck på knappen \"Öppna inställningar\"",
        step2 = "Aktivera \"Öppna länkar\" för maps.apple.com",
        step3 = "Klart! Apple Maps-länkar öppnas nu automatiskt i Google Maps.",
        btnSettings = "Öppna inställningar",
        statusActive = "Länkar är aktiverade",
        statusInactive = "Länkar är inte aktiva än",
        statusHint = "Status kan inte kontrolleras på äldre Android-versioner.",
        famwakeTitle = "FamWake – Familjeväckarklocka",
        famwakePromo = "Från samma utvecklare",
        famwakeDesc = "FamWake samordnar morgonen för hela familjen – badrumstider, frukost och uppstigning.",
        famwakeButton = "Läs mer",
        langToggle = "SV",
        btnFeedback = "Support",
        pauseTitle = "Pausa omdirigering",
        pauseDesc = "Avbryt tillfälligt alla länkomdirigeringar",
        statusPaused = "Omdirigering är pausad",
        selectLanguageTitle = "Välj språk",
        systemLanguageAuto = "Systemstandard (Automatisk)",
        btnRateApp = "Betygsätt appen",
        privacyNote = "100% integritetsvänlig: alla omdirigeringar sker lokalt. Ingen dataindsamling.",
        privacyNotePlay = "100% integritetsvänlig: alla omdirigeringar sker lokalt. Ingen insamling av personuppgifter eller platsdata.",
        testLinkTitle = "Länktester & urklipp",
        testLinkHint = "Ange Apple Maps-länk här...",
        btnPasteClipboard = "Klistra in",
        btnTestLink = "Testa i %s",
        testLinkConvertedLabel = "Konverterad mål-URI:",
        pauseIndefinitely = "Tills vidare",
        pause1Hour = "1 timme",
        pause8Hours = "8 timmar",
        pauseUntilTomorrow = "Till imorgon bitti",
        dialogPauseTitle = "Välj pauslängd",
        menuSettingsAbout = "Inställningar och Om",
        aboutTitle = "Om MapFlip",
        appVersionLabel = "Version",
        btnClose = "Stäng",
        sectionLanguage = "Språk",
        sectionTheme = "Utseende",
        themeSystem = "Systemstandard",
        themeLight = "Ljust",
        themeDark = "Mörkt",
        btnDonate = "Donera",
        donateSubtitle = "Stöd utvecklingen på Ko-fi",
        privacyPolicyTitle = "Integritetspolicy",
        impressumTitle = "Juridisk information (Impressum)",
        sectionGeneral = "Allmänt",
        sectionAbout = "Om appen",
        quickGuideTitle = "Snabbguide",
        btnCopyLink = "Kopiera länk",
        linkCopiedToast = "Länk kopierad till urklipp",
        btnShareLink = "Dela länk",
        btnClearInput = "Rensa",
        clipboardDetectedTitle = "Kartlänk i urklipp",
        btnOpenInApp = "Öppna i %s",
        actionExpand = "Fäll ut",
        actionCollapse = "Fäll ihop",
        appNotInstalled = "%s är inte installerad",
        targetAppOpenError = "Målappen kunde inte öppnas",
        statusInstalled = "Installerad",
        statusNotInstalled = "Inte installerad",
        tileSetupRequired = "Inställning krävs",
        setupSheetTitle = "Konfigurera kartlänkar",
        setupSheetSubtitle = "Android 12+ kräver manuell bekräftelse av stödda kartlänkar.",
        setupStep1Title = "Öppna systeminställningar",
        setupStep1Desc = "Tryck på knappen nedan för att öppna MapFlips appinställningar.",
        setupStep2Title = "Välj \"Öppna som standard\"",
        setupStep2Desc = "Tryck på \"Öppna länkar som stöds\" eller \"Lägg till länk\".",
        setupStep3Title = "Aktivera kartlänkar",
        setupStep3Desc = "Markera alla stödda karttjänster (Apple, Bing, OSM, HERE osv.).",
        setupAltTitle = "Fungerar direkt utan inställningar:",
        setupAltShare = "Delningsmeny: Dela valfri kartlänk via Androids delningsmeny direkt med MapFlip.",
        setupAltClipboard = "Urklipp: Kopiera en kartlänk och öppna MapFlip för omedelbar omdirigering.",
        setupBtnOpenSettings = "Öppna systeminställningar",
        setupBtnDismiss = "Fortsätt utan inställningar",
        setupStatusAllActive = "%d av %d länkar aktiva",
        setupStatusPartial = "%d av %d länkar aktiva – tryck för att lägga till fler",
        setupStatusNone = "Inga länkar aktiva – konfigurering krävs",
        menuSetupGuide = "Konfigurationsguide (Android 12+)",
    )

    val ES = EN.copy(
        tagline = "Automático. Invisible.",
        setupTitle = "Cómo funciona",
        step1 = "Toca el botón \"Abrir Ajustes\"",
        step2 = "Activa \"Abrir enlaces\" para maps.apple.com",
        step3 = "¡Listo! Los enlaces de Apple Maps se abrirán automáticamente en Google Maps.",
        btnSettings = "Abrir Ajustes",
        statusActive = "Los enlaces están activados",
        statusInactive = "Los enlaces aún no están activos",
        statusHint = "El estado no se puede verificar en versiones anteriores de Android.",
        famwakeTitle = "FamWake – Despertador Familiar",
        famwakePromo = "Del mismo desarrollador",
        famwakeDesc = "FamWake coordina las mañanas de toda la familia: turnos de baño, desayuno y despertar.",
        famwakeButton = "Más información",
        langToggle = "ES",
        btnFeedback = "Soporte",
        pauseTitle = "Pausar redirección",
        pauseDesc = "Suspender temporalmente todas las redirecciones de enlaces",
        statusPaused = "La redirección está pausada",
        selectLanguageTitle = "Seleccionar idioma",
        systemLanguageAuto = "Predeterminado del sistema (Auto)",
        btnRateApp = "Calificar app",
        privacyNote = "100% privado: todas las redirecciones se procesan localmente. Sin recopilación de datos.",
        privacyNotePlay = "100% privado: todas las redirecciones se procesan localmente. Sin recopilación de datos personales ni ubicaciones.",
        testLinkTitle = "Probador de enlaces y portapapeles",
        testLinkHint = "Introduce aquí el enlace de Apple Maps...",
        btnPasteClipboard = "Pegar",
        btnTestLink = "Probar en %s",
        testLinkConvertedLabel = "URI de destino convertida:",
        pauseIndefinitely = "Indefinidamente",
        pause1Hour = "1 hora",
        pause8Hours = "8 horas",
        pauseUntilTomorrow = "Hasta mañana por la mañana",
        dialogPauseTitle = "Seleccionar duración de pausa",
        menuSettingsAbout = "Ajustes e Información",
        aboutTitle = "Acerca de MapFlip",
        appVersionLabel = "Versión",
        btnClose = "Cerrar",
        sectionLanguage = "Idioma",
        sectionTheme = "Apariencia",
        themeSystem = "Predeterminado del sistema",
        themeLight = "Claro",
        themeDark = "Oscuro",
        btnDonate = "Donar",
        donateSubtitle = "Apoya el desarrollo en Ko-fi",
        privacyPolicyTitle = "Política de privacidad",
        impressumTitle = "Aviso Legal (Impressum)",
        sectionGeneral = "General",
        sectionAbout = "Acerca de la app",
        quickGuideTitle = "Guía rápida",
        btnCopyLink = "Copiar enlace",
        linkCopiedToast = "Enlace copiado al portapapeles",
        btnShareLink = "Compartir enlace",
        btnClearInput = "Borrar",
        clipboardDetectedTitle = "Enlace de mapa en el portapapeles",
        btnOpenInApp = "Abrir en %s",
        actionExpand = "Desplegar",
        actionCollapse = "Plegar",
        appNotInstalled = "%s no está instalada",
        targetAppOpenError = "No se pudo abrir la app de destino",
        statusInstalled = "Instalada",
        statusNotInstalled = "No instalada",
        tileSetupRequired = "Configuración requerida",
        setupSheetTitle = "Configurar enlaces de mapas",
        setupSheetSubtitle = "Android 12+ requiere confirmar manualmente los enlaces de mapas compatibles.",
        setupStep1Title = "Abrir ajustes del sistema",
        setupStep1Desc = "Toca el botón inferior para abrir los ajustes de la aplicación MapFlip.",
        setupStep2Title = "Seleccionar \"Abrir de forma predeterminada\"",
        setupStep2Desc = "Toca \"Abrir enlaces compatibles\" o \"Añadir enlace\".",
        setupStep3Title = "Activar enlaces de mapas",
        setupStep3Desc = "Marca todos los dominios de mapas deseados (Apple, Bing, OSM, HERE, etc.).",
        setupAltTitle = "Funciona al instante sin configuración:",
        setupAltShare = "Menú Compartir: Comparte cualquier enlace de mapa mediante el menú Compartir de Android directamente con MapFlip.",
        setupAltClipboard = "Portapapeles: Copia un enlace de mapa y abre MapFlip para una redirección instantánea.",
        setupBtnOpenSettings = "Abrir ajustes del sistema",
        setupBtnDismiss = "Continuar sin configurar",
        setupStatusAllActive = "%d de %d enlaces activos",
        setupStatusPartial = "%d de %d enlaces activos – toca para añadir más",
        setupStatusNone = "Ningún enlace activo – configuración requerida",
        menuSetupGuide = "Guía de configuración (Android 12+)",
    )

    val TR = EN.copy(
        tagline = "Otomatik. Görünmez.",
        setupTitle = "Nasıl çalışır",
        step1 = "Aşağıdaki \"Ayarları Aç\" düğmesine dokunun",
        step2 = "maps.apple.com için \"Bağlantıları aç\"ı etkinleştirin",
        step3 = "Bitti! Apple Maps bağlantıları artık Google Maps'te otomatik açılacak.",
        btnSettings = "Ayarları Aç",
        statusActive = "Bağlantılar etkinleştirildi",
        statusInactive = "Bağlantılar henüz etkin değil",
        statusHint = "Eski Android sürümlerinde durum kontrol edilemez.",
        famwakeTitle = "FamWake – Aile Çalar Saati",
        famwakePromo = "Aynı geliştiriciden",
        famwakeDesc = "FamWake tüm aile için sabahı koordine eder – banyo saatleri, kahvaltı ve uyanma.",
        famwakeButton = "Daha fazla bilgi",
        langToggle = "TR",
        btnFeedback = "Destek",
        pauseTitle = "Yönlendirmeyi Duraklat",
        pauseDesc = "Tüm bağlantı yönlendirmelerini geçici olarak durdurun",
        statusPaused = "Yönlendirme duraklatıldı",
        selectLanguageTitle = "Dil Seçin",
        systemLanguageAuto = "Sistem Varsayılanı (Otomatik)",
        btnRateApp = "Uygulamayı değerlendir",
        privacyNote = "100% gizlilik dostu: Tüm yönlendirmeler yerel olarak yapılır. Veri toplama yoktur.",
        privacyNotePlay = "100% gizlilik dostu: Tüm yönlendirmeler yerel olarak yapılır. Kişisel veri veya konum takibi yoktur.",
        testLinkTitle = "Bağlantı Test Edici ve Pano",
        testLinkHint = "Buraya Apple Maps bağlantısını girin...",
        btnPasteClipboard = "Yapıştır",
        btnTestLink = "%s'te Test Et",
        testLinkConvertedLabel = "Dönüştürülen Hedef URI:",
        pauseIndefinitely = "Süresiz",
        pause1Hour = "1 Saat",
        pause8Hours = "8 Saat",
        pauseUntilTomorrow = "Yarın sabaha kadar",
        dialogPauseTitle = "Duraklatma Süresi Seçin",
        menuSettingsAbout = "Ayarlar & Hakkında",
        aboutTitle = "MapFlip Hakkında",
        appVersionLabel = "Sürüm",
        btnClose = "Kapat",
        sectionLanguage = "Dil",
        sectionTheme = "Görünüm",
        themeSystem = "Sistem varsayılanı",
        themeLight = "Açık",
        themeDark = "Koyu",
        btnDonate = "Bağış Yap",
        donateSubtitle = "Geliştirmeyi Ko-fi üzerinden destekleyin",
        privacyPolicyTitle = "Gizlilik Politikası",
        impressumTitle = "Yasal Bildirim (Impressum)",
        sectionGeneral = "Genel",
        sectionAbout = "Uygulama hakkında",
        quickGuideTitle = "Kurulum Kılavuzu",
        btnCopyLink = "Bağlantıyı kopyala",
        linkCopiedToast = "Bağlantı panoya kopyalandı",
        btnShareLink = "Bağlantıyı paylaş",
        btnClearInput = "Temizle",
        clipboardDetectedTitle = "Panodaki harita bağlantısı",
        btnOpenInApp = "%s ile Aç",
        actionExpand = "Genişlet",
        actionCollapse = "Daralt",
        appNotInstalled = "%s yüklü değil",
        targetAppOpenError = "Hedef uygulama açılamadı",
        statusInstalled = "Yüklü",
        statusNotInstalled = "Yüklü değil",
        tileSetupRequired = "Kurulum gerekli",
        setupSheetTitle = "Harita bağlantılarını ayarla",
        setupSheetSubtitle = "Android 12+, desteklenen harita bağlantılarının manuel olarak onaylanmasını gerektirir.",
        setupStep1Title = "Sistem ayarlarını aç",
        setupStep1Desc = "MapFlip uygulama ayarlarını açmak için aşağıdaki düğmeye dokunun.",
        setupStep2Title = "\"Varsayılan olarak aç\"ı seçin",
        setupStep2Desc = "\"Desteklenen bağlantıları aç\" veya \"Bağlantı ekle\"ye dokunun.",
        setupStep3Title = "Harita bağlantılarını etkinleştirin",
        setupStep3Desc = "Tüm desteklenen harita alan adlarını işaretleyin (Apple, Bing, OSM, HERE vb.).",
        setupAltTitle = "Kurulum olmadan hemen çalışır:",
        setupAltShare = "Paylaş Menüsü: Herhangi bir harita bağlantısını Android Paylaş menüsüyle doğrudan MapFlip ile paylaşın.",
        setupAltClipboard = "Pano: Bir harita bağlantısını kopyalayın ve anında yönlendirme için MapFlip'i açın.",
        setupBtnOpenSettings = "Sistem ayarlarını aç",
        setupBtnDismiss = "Ayar yapmadan devam et",
        setupStatusAllActive = "%d / %d bağlantı etkin",
        setupStatusPartial = "%d / %d bağlantı etkin – daha fazlasını eklemek için dokunun",
        setupStatusNone = "Etkin bağlantı yok – kurulum gerekli",
        menuSetupGuide = "Kurulum Kılavuzu (Android 12+)",
    )

    val KO = EN.copy(
        tagline = "자동. 투명함.",
        setupTitle = "설정 방법",
        step1 = "\"설정 열기\" 버튼을 탭하세요",
        step2 = "maps.apple.com에 대해 \"지원되는 링크 열기\"를 활성화하세요",
        step3 = "완료! 이제 Apple Maps 링크가 Google Maps에서 자동으로 열립니다.",
        btnSettings = "설정 열기",
        statusActive = "링크가 활성화되었습니다",
        statusInactive = "링크가 아직 활성화되지 않았습니다",
        statusHint = "이전 Android 버전에서는 상태를 확인할 수 없습니다.",
        famwakeTitle = "FamWake – 패밀리 알람 시계",
        famwakePromo = "동일한 개발자의 추천 앱",
        famwakeDesc = "FamWake는 욕실 사용 순서, 아침 식사, 기상 시간 등 온 가족의 아침 일과를 조율합니다.",
        famwakeButton = "자세히 알아보기",
        langToggle = "KO",
        btnFeedback = "지원 및 문의",
        pauseTitle = "리디렉션 일시중지",
        pauseDesc = "모든 지도 링크 리디렉션을 일시적으로 중지합니다",
        statusPaused = "리디렉션이 일시중지됨",
        selectLanguageTitle = "언어 선택",
        systemLanguageAuto = "시스템 기본값 (자동)",
        btnRateApp = "앱 평가하기",
        privacyNote = "100% 개인정보 보호: 모든 링크는 기기 내에서 로컬로 변환되며 데이터를 수집하지 않습니다.",
        privacyNotePlay = "100% 개인정보 보호: 모든 링크는 기기 내에서 로컬로 변환되며 개인정보나 위치 데이터를 수집하지 않습니다.",
        testLinkTitle = "링크 테스터 및 클립보드",
        testLinkHint = "Apple Maps 링크를 여기에 입력하세요...",
        btnPasteClipboard = "붙여넣기",
        btnTestLink = "%s에서 테스트",
        testLinkConvertedLabel = "변환된 대상 URI:",
        pauseIndefinitely = "무기한",
        pause1Hour = "1시간",
        pause8Hours = "8시간",
        pauseUntilTomorrow = "내일 아침까지",
        dialogPauseTitle = "일시중지 시간 선택",
        menuSettingsAbout = "설정 및 정보",
        aboutTitle = "MapFlip 정보",
        appVersionLabel = "버전",
        btnClose = "닫기",
        sectionLanguage = "언어",
        sectionTheme = "화면 테마",
        themeSystem = "시스템 기본값",
        themeLight = "라이트 모드",
        themeDark = "다크 모드",
        btnDonate = "후원하기",
        donateSubtitle = "Ko-fi에서 개발 후원하기",
        privacyPolicyTitle = "개인정보 처리방침",
        impressumTitle = "법적 고지 (Impressum)",
        sectionGeneral = "일반",
        sectionAbout = "앱 정보",
        quickGuideTitle = "빠른 시작 가이드",
        btnCopyLink = "링크 복사",
        linkCopiedToast = "링크가 클립보드에 복사되었습니다",
        btnShareLink = "링크 공유",
        btnClearInput = "지우기",
        clipboardDetectedTitle = "클립보드의 지도 링크",
        btnOpenInApp = "%s에서 열기",
        actionExpand = "펼치기",
        actionCollapse = "접기",
        appNotInstalled = "%s 앱이 설치되어 있지 않습니다",
        targetAppOpenError = "대상 앱을 열 수 없습니다",
        statusInstalled = "설치됨",
        statusNotInstalled = "설치되지 않음",
        tileSetupRequired = "설정이 필요합니다",
        setupSheetTitle = "지도 링크 설정",
        setupSheetSubtitle = "Android 12 이상에서는 지원되는 지도 링크를 수동으로 승인해야 합니다.",
        setupStep1Title = "시스템 설정 열기",
        setupStep1Desc = "아래 버튼을 눌러 MapFlip의 앱 설정 화면을 엽니다.",
        setupStep2Title = "\"기본으로 열기\" 선택",
        setupStep2Desc = "\"지원되는 링크 열기\" 또는 \"링크 추가\"를 누릅니다.",
        setupStep3Title = "지도 링크 활성화",
        setupStep3Desc = "지원되는 모든 지도 도메인(Apple, Bing, OSM, HERE 등)을 선택합니다.",
        setupAltTitle = "설정 없이 바로 사용하는 방법:",
        setupAltShare = "공유 메뉴: 지도 링크를 Android 공유 메뉴를 통해 MapFlip으로 직접 공유하세요.",
        setupAltClipboard = "클립보드: 지도 링크를 복사하고 MapFlip을 열면 즉시 리디렉션됩니다.",
        setupBtnOpenSettings = "시스템 설정 열기",
        setupBtnDismiss = "설정 없이 계속",
        setupStatusAllActive = "%d / %d 링크 활성화됨",
        setupStatusPartial = "%d / %d 링크 활성화됨 – 탭하여 추가",
        setupStatusNone = "활성화된 링크 없음 – 설정 필요",
        menuSetupGuide = "설정 가이드 (Android 12+)",
    )

    val ZH_CN = EN.copy(
        tagline = "自动。无缝。",
        setupTitle = "使用方法",
        step1 = "点击“打开设置”按钮",
        step2 = "为 maps.apple.com 启用“打开支持的链接”",
        step3 = "完成！Apple Maps 链接将自动在 Google Maps 中打开。",
        btnSettings = "打开设置",
        statusActive = "链接已启用",
        statusInactive = "链接尚未激活",
        statusHint = "旧版 Android 无法检查此状态。",
        famwakeTitle = "FamWake – 家庭早晨闹钟",
        famwakePromo = "同一开发者出品",
        famwakeDesc = "FamWake 协调全家人的清晨节奏 – 洗漱轮流、早餐与起床时间安排。",
        famwakeButton = "了解更多",
        langToggle = "ZH",
        btnFeedback = "技术支持",
        pauseTitle = "暂停重定向",
        pauseDesc = "暂时停用所有地图链接重定向",
        statusPaused = "重定向已暂停",
        selectLanguageTitle = "选择语言",
        systemLanguageAuto = "系统默认（自动）",
        btnRateApp = "评价应用",
        privacyNote = "100% 保护隐私：所有链接均在本地转换，不收集任何数据。",
        privacyNotePlay = "100% 保护隐私：所有链接均在本地转换，不收集任何个人数据或位置信息。",
        testLinkTitle = "链接测试与剪贴板",
        testLinkHint = "在此输入 Apple Maps 链接...",
        btnPasteClipboard = "粘贴",
        btnTestLink = "在 %s 中测试",
        testLinkConvertedLabel = "转换后的目标 URI:",
        pauseIndefinitely = "无限期",
        pause1Hour = "1 小时",
        pause8Hours = "8 小时",
        pauseUntilTomorrow = "直到明早",
        dialogPauseTitle = "选择暂停时长",
        menuSettingsAbout = "设置与关于",
        aboutTitle = "关于 MapFlip",
        appVersionLabel = "版本",
        btnClose = "关闭",
        sectionLanguage = "语言",
        sectionTheme = "外观",
        themeSystem = "跟随系统",
        themeLight = "浅色",
        themeDark = "深色",
        btnDonate = "赞助支持",
        donateSubtitle = "在 Ko-fi 上支持开发者",
        privacyPolicyTitle = "隐私政策",
        impressumTitle = "法律声明 (Impressum)",
        sectionGeneral = "通用",
        sectionAbout = "关于应用",
        quickGuideTitle = "快速指南",
        btnCopyLink = "复制链接",
        linkCopiedToast = "链接已复制到剪贴板",
        btnShareLink = "分享链接",
        btnClearInput = "清除",
        clipboardDetectedTitle = "剪贴板中的地图链接",
        btnOpenInApp = "在 %s 中打开",
        actionExpand = "展开",
        actionCollapse = "折叠",
        appNotInstalled = "未安装 %s",
        targetAppOpenError = "无法打开目标应用",
        statusInstalled = "已安装",
        statusNotInstalled = "未安装",
        tileSetupRequired = "需要设置",
        setupSheetTitle = "设置地图链接",
        setupSheetSubtitle = "Android 12+ 需要手动确认支持的地图链接。",
        setupStep1Title = "打开系统设置",
        setupStep1Desc = "点击下方按钮打开 MapFlip 的应用设置。",
        setupStep2Title = "选择“默认打开”",
        setupStep2Desc = "点击“打开支持的链接”或“添加链接”。",
        setupStep3Title = "启用地图链接",
        setupStep3Desc = "勾选所有支持的地图服务（Apple、Bing、OSM、HERE 等）。",
        setupAltTitle = "无需设置即可即时使用：",
        setupAltShare = "分享菜单：通过 Android 分享菜单将任何地图链接直接分享到 MapFlip。",
        setupAltClipboard = "剪贴板：复制地图链接并打开 MapFlip 即可瞬间重定向。",
        setupBtnOpenSettings = "打开系统设置",
        setupBtnDismiss = "暂不设置继续",
        setupStatusAllActive = "已激活 %d / %d 个链接",
        setupStatusPartial = "已激活 %d / %d 个链接 – 点击添加更多",
        setupStatusNone = "未激活任何链接 – 需要设置",
        menuSetupGuide = "设置指南 (Android 12+)",
    )

    val ZH_TW = EN.copy(
        tagline = "自動。無縫。",
        setupTitle = "使用步驟",
        step1 = "點擊「開啟設定」按鈕",
        step2 = "為 maps.apple.com 啟用「開啟支援的連結」",
        step3 = "完成！Apple Maps 連結將自動在 Google Maps 中開啟。",
        btnSettings = "開啟設定",
        statusActive = "連結已啟用",
        statusInactive = "連結尚未啟用",
        statusHint = "舊版 Android 無法檢查此狀態。",
        famwakeTitle = "FamWake – 家庭早晨鬧鐘",
        famwakePromo = "同位開發者推薦",
        famwakeDesc = "FamWake 協調整個家庭的早晨節奏 – 盥洗順序、早餐與起床時間安排。",
        famwakeButton = "了解更多",
        langToggle = "ZH-TW",
        btnFeedback = "技術支援",
        pauseTitle = "暫停重新導向",
        pauseDesc = "暫時停止所有地圖連結轉向",
        statusPaused = "重新導向已暫停",
        selectLanguageTitle = "選擇語言",
        systemLanguageAuto = "系統預設（自動）",
        btnRateApp = "為應用評分",
        privacyNote = "100% 重視隱私：所有轉換均在裝置本機完成，絕不收集任何資料。",
        privacyNotePlay = "100% 重視隱私：所有轉換均在裝置本機完成，絕不收集任何個人資料或位置資訊。",
        testLinkTitle = "連結測試與剪貼簿",
        testLinkHint = "在此輸入 Apple Maps 連結...",
        btnPasteClipboard = "貼上",
        btnTestLink = "在 %s 中測試",
        testLinkConvertedLabel = "轉換後的目標 URI:",
        pauseIndefinitely = "無限期",
        pause1Hour = "1 小時",
        pause8Hours = "8 小時",
        pauseUntilTomorrow = "直到明天早上",
        dialogPauseTitle = "選擇暫停時間",
        menuSettingsAbout = "設定與關於",
        aboutTitle = "關於 MapFlip",
        appVersionLabel = "版本",
        btnClose = "關閉",
        sectionLanguage = "語言",
        sectionTheme = "外觀",
        themeSystem = "系統預設",
        themeLight = "淺色",
        themeDark = "深色",
        btnDonate = "贊助支持",
        donateSubtitle = "在 Ko-fi 上支持開發者",
        privacyPolicyTitle = "隱私權政策",
        impressumTitle = "法律聲明 (Impressum)",
        sectionGeneral = "一般",
        sectionAbout = "關於應用程式",
        quickGuideTitle = "快速上手",
        btnCopyLink = "複製連結",
        linkCopiedToast = "連結已複製到剪貼簿",
        btnShareLink = "分享連結",
        btnClearInput = "清除",
        clipboardDetectedTitle = "剪貼簿中的地圖連結",
        btnOpenInApp = "在 %s 中開啟",
        actionExpand = "展開",
        actionCollapse = "收合",
        appNotInstalled = "尚未安裝 %s",
        targetAppOpenError = "無法開啟目標應用程式",
        statusInstalled = "已安裝",
        statusNotInstalled = "未安裝",
        tileSetupRequired = "需要設定",
        setupSheetTitle = "設定地圖連結",
        setupSheetSubtitle = "Android 12+ 需要手動確認支援的地圖連結。",
        setupStep1Title = "開啟系統設定",
        setupStep1Desc = "點擊下方按鈕開啟 MapFlip 的應用程式設定。",
        setupStep2Title = "選擇「預設開啟」",
        setupStep2Desc = "點擊「開啟支援的連結」或「新增連結」。",
        setupStep3Title = "啟用地圖連結",
        setupStep3Desc = "勾選所有支援的地圖服務（Apple、Bing、OSM、HERE 等）。",
        setupAltTitle = "無需設定即可即時使用：",
        setupAltShare = "分享選單：透過 Android 分享選單將任何地圖連結直接分享到 MapFlip。",
        setupAltClipboard = "剪貼簿：複製地圖連結並開啟 MapFlip 即可立即重新導向。",
        setupBtnOpenSettings = "開啟系統設定",
        setupBtnDismiss = "暫不設定繼續",
        setupStatusAllActive = "已啟用 %d / %d 個連結",
        setupStatusPartial = "已啟用 %d / %d 個連結 – 點擊新增更多",
        setupStatusNone = "未啟用任何連結 – 需要設定",
        menuSetupGuide = "設定指南 (Android 12+)",
    )

    val AR = EN.copy(
        tagline = "تلقائي. غير مرئي.",
        setupTitle = "كيفية البدء",
        step1 = "اضغط على زر \"فتح الإعدادات\"",
        step2 = "فعّل \"فتح الروابط المعتمدة\" لـ maps.apple.com",
        step3 = "تم! ستفتح روابط Apple Maps تلقائياً في Google Maps.",
        btnSettings = "فتح الإعدادات",
        statusActive = "الروابط مفعلة",
        statusInactive = "الروابط غير مفعلة بعد",
        statusHint = "لا يمكن التحقق من الحالة في إصدارات أندرويد القديمة.",
        famwakeTitle = "FamWake – منبه العائلة الذكي",
        famwakePromo = "من نفس المطور",
        famwakeDesc = "ينسّق تطبيق FamWake صباح العائلة بأكملها – مواعيد الحمام والإفطار والاستيقاظ.",
        famwakeButton = "اكتشف المزيد",
        langToggle = "AR",
        btnFeedback = "الدعم والمساعدة",
        pauseTitle = "إيقاف مؤقت لإعادة التوجيه",
        pauseDesc = "تعطيل إعادة التوجيه مؤقتاً لجميع الروابط",
        statusPaused = "إعادة التوجيه متوقفة مؤقتاً",
        selectLanguageTitle = "اختر اللغة",
        systemLanguageAuto = "افتراضي النظام (تلقائي)",
        btnRateApp = "تقييم التطبيق",
        privacyNote = "خصوصية 100%: تتم جميع التحويلات محلياً على جهازك دون جمع أي بيانات.",
        privacyNotePlay = "خصوصية 100%: تتم جميع التحويلات محلياً على جهازك دون جمع أي بيانات شخصية أو بيانات الموقع.",
        testLinkTitle = "اختبار الروابط والحافظة",
        testLinkHint = "أدخل رابط Apple Maps هنا...",
        btnPasteClipboard = "لصق",
        btnTestLink = "اختبار في %s",
        testLinkConvertedLabel = "الرابط الهدف المحول:",
        pauseIndefinitely = "إلى أجل غير مسمى",
        pause1Hour = "ساعة واحدة",
        pause8Hours = "8 ساعات",
        pauseUntilTomorrow = "حتى صباح الغد",
        dialogPauseTitle = "اختر مدة الإيقاف المؤقت",
        menuSettingsAbout = "الإعدادات وحول التطبيق",
        aboutTitle = "حول MapFlip",
        appVersionLabel = "الإصدار",
        btnClose = "إغلاق",
        sectionLanguage = "اللغة",
        sectionTheme = "المظهر",
        themeSystem = "افتراضي النظام",
        themeLight = "فاتح",
        themeDark = "داكن",
        btnDonate = "تبرع",
        donateSubtitle = "ادعم التطوير على Ko-fi",
        privacyPolicyTitle = "سياسة الخصوصية",
        impressumTitle = "الإشعار القانوني (Impressum)",
        sectionGeneral = "عام",
        sectionAbout = "حول التطبيق",
        quickGuideTitle = "دليل الإعداد السريع",
        btnCopyLink = "نسخ الرابط",
        linkCopiedToast = "تم نسخ الرابط إلى الحافظة",
        btnShareLink = "مشاركة الرابط",
        btnClearInput = "مسح",
        clipboardDetectedTitle = "رابط خريطة في الحافظة",
        btnOpenInApp = "فتح في %s",
        actionExpand = "توسيع",
        actionCollapse = "طي",
        appNotInstalled = "%s غير مثبت",
        targetAppOpenError = "تعذر فتح التطبيق المطلوب",
        statusInstalled = "مثبت",
        statusNotInstalled = "غير مثبت",
        tileSetupRequired = "الإعداد مطلوب",
        setupSheetTitle = "إعداد روابط الخرائط",
        setupSheetSubtitle = "يتطلب Android 12+ تأكيد روابط الخرائط المدعومة يدوياً.",
        setupStep1Title = "فتح إعدادات النظام",
        setupStep1Desc = "اضغط على الزر أدناه لفتح إعدادات تطبيق MapFlip.",
        setupStep2Title = "اختر \"الفتح افتراضياً\"",
        setupStep2Desc = "اضغط على \"فتح الروابط المدعومة\" أو \"إضافة روابط\".",
        setupStep3Title = "تفعيل روابط الخرائط",
        setupStep3Desc = "حدد جميع نطاقات الخرائط المدعومة (Apple و Bing و OSM و HERE وغيرها).",
        setupAltTitle = "يعمل فوراً بدون إعداد:",
        setupAltShare = "قائمة المشاركة: شارك أي رابط خريطة عبر قائمة مشاركة Android مباشرة مع MapFlip.",
        setupAltClipboard = "الحافظة: انسخ رابط الخريطة وافتح MapFlip لإعادة التوجيه الفوري.",
        setupBtnOpenSettings = "فتح إعدادات النظام",
        setupBtnDismiss = "المتابعة بدون إعداد",
        setupStatusAllActive = "%d من %d روابط نشطة",
        setupStatusPartial = "%d من %d روابط نشطة – اضغط لإضافة المزيد",
        setupStatusNone = "لا توجد روابط نشطة – يلزم الإعداد",
        menuSetupGuide = "دليل الإعداد (Android 12+)",
    )

    val RU = EN.copy(
        tagline = "Автоматически. Незаметно.",
        setupTitle = "Как это работает",
        step1 = "Нажмите кнопку «Открыть настройки»",
        step2 = "Включите «Открывать поддерживаемые ссылки» для maps.apple.com",
        step3 = "Готово! Ссылки Apple Maps теперь автоматически открываются в Google Maps.",
        btnSettings = "Открыть настройки",
        statusActive = "Ссылки включены",
        statusInactive = "Ссылки еще не активны",
        statusHint = "Статус нельзя проверить на старых версиях Android.",
        famwakeTitle = "FamWake – Семейный будильник",
        famwakePromo = "От того же разработчика",
        famwakeDesc = "FamWake координирует утро для всей семьи — очередь в ванную, завтрак и подъем.",
        famwakeButton = "Узнать больше",
        langToggle = "RU",
        btnFeedback = "Поддержка",
        pauseTitle = "Приостановить перенаправление",
        pauseDesc = "Временно отключить все перенаправления ссылок",
        statusPaused = "Перенаправление приостановлено",
        selectLanguageTitle = "Выбрать язык",
        systemLanguageAuto = "Системный (авто)",
        btnRateApp = "Оценить приложение",
        privacyNote = "100% конфиденциальность: вся обработка выполняется локально на устройстве. Без сбора данных.",
        privacyNotePlay = "100% конфиденциальность: вся обработка выполняется локально на устройстве. Без сбора персональных данных и геопозиции.",
        testLinkTitle = "Тестер ссылок и буфер обмена",
        testLinkHint = "Введите ссылку Apple Maps здесь...",
        btnPasteClipboard = "Вставить",
        btnTestLink = "Проверить в %s",
        testLinkConvertedLabel = "Преобразованный URI:",
        pauseIndefinitely = "Бессрочно",
        pause1Hour = "1 час",
        pause8Hours = "8 часов",
        pauseUntilTomorrow = "До завтрашнего утра",
        dialogPauseTitle = "Выберите время паузы",
        menuSettingsAbout = "Настройки и о приложении",
        aboutTitle = "О приложении MapFlip",
        appVersionLabel = "Версия",
        btnClose = "Закрыть",
        sectionLanguage = "Язык",
        sectionTheme = "Тема оформления",
        themeSystem = "Системная",
        themeLight = "Светлая",
        themeDark = "Темная",
        btnDonate = "Поддержать",
        donateSubtitle = "Поддержать разработку на Ko-fi",
        privacyPolicyTitle = "Политика конфиденциальности",
        impressumTitle = "Правовая информация (Impressum)",
        sectionGeneral = "Общие",
        sectionAbout = "О приложении",
        quickGuideTitle = "Инструкция",
        btnCopyLink = "Скопировать ссылку",
        linkCopiedToast = "Ссылка скопирована в буфер обмена",
        btnShareLink = "Поделиться ссылкой",
        btnClearInput = "Очистить",
        clipboardDetectedTitle = "Ссылка на карту в буфере",
        btnOpenInApp = "Открыть в %s",
        actionExpand = "Развернуть",
        actionCollapse = "Свернуть",
        appNotInstalled = "Приложение %s не установлено",
        targetAppOpenError = "Не удалось открыть целевое приложение",
        statusInstalled = "Установлено",
        statusNotInstalled = "Не установлено",
        tileSetupRequired = "Требуется настройка",
        setupSheetTitle = "Настройка ссылок карт",
        setupSheetSubtitle = "В Android 12+ требуется вручную подтвердить поддерживаемые ссылки карт.",
        setupStep1Title = "Открыть настройки системы",
        setupStep1Desc = "Нажмите кнопку ниже, чтобы открыть настройки MapFlip.",
        setupStep2Title = "Выберите \"Открывать по умолчанию\"",
        setupStep2Desc = "Нажмите \"Открывать поддерживаемые ссылки\" или \"Добавить ссылки\".",
        setupStep3Title = "Включить ссылки карт",
        setupStep3Desc = "Отметьте все поддерживаемые службы карт (Apple, Bing, OSM, HERE и др.).",
        setupAltTitle = "Работает мгновенно без настройки:",
        setupAltShare = "Меню \"Поделиться\": Отправьте любую ссылку на карту через меню Android прямо в MapFlip.",
        setupAltClipboard = "Буфер обмена: Скопируйте ссылку на карту и откройте MapFlip для мгновенного перенаправления.",
        setupBtnOpenSettings = "Открыть настройки системы",
        setupBtnDismiss = "Продолжить без настройки",
        setupStatusAllActive = "%d из %d ссылок активно",
        setupStatusPartial = "%d из %d ссылок активно – нажмите для добавления",
        setupStatusNone = "Нет активных ссылок – требуется настройка",
        menuSetupGuide = "Инструкция по настройке (Android 12+)",
    )

    val ID = EN.copy(
        tagline = "Otomatis. Tak Terlihat.",
        setupTitle = "Cara Penggunaan",
        step1 = "Ketuk tombol \"Buka Pengaturan\"",
        step2 = "Aktifkan \"Buka tautan yang didukung\" untuk maps.apple.com",
        step3 = "Selesai! Tautan Apple Maps akan otomatis dibuka di Google Maps.",
        btnSettings = "Buka Pengaturan",
        statusActive = "Tautan aktif",
        statusInactive = "Tautan belum aktif",
        statusHint = "Status tidak dapat diperiksa pada versi Android lama.",
        famwakeTitle = "FamWake – Jam Weker Keluarga",
        famwakePromo = "Dari pengembang yang sama",
        famwakeDesc = "FamWake mengoordinasikan pagi untuk seluruh keluarga – giliran kamar mandi, sarapan, dan bangun tidur.",
        famwakeButton = "Pelajari selengkapnya",
        langToggle = "ID",
        btnFeedback = "Bantuan & Dukungan",
        pauseTitle = "Jeda Pengalihan",
        pauseDesc = "Hentikan sementara semua pengalihan tautan peta",
        statusPaused = "Pengalihan dijeda",
        selectLanguageTitle = "Pilih Bahasa",
        systemLanguageAuto = "Default Sistem (Otomatis)",
        btnRateApp = "Beri Nilai Aplikasi",
        privacyNote = "100% ramah privasi: Semua konversi diproses secara lokal di perangkat. Tanpa pengumpulan data.",
        privacyNotePlay = "100% ramah privasi: Semua konversi diproses secara lokal di perangkat. Tanpa pengumpulan data pribadi atau lokasi.",
        testLinkTitle = "Penguji Tautan & Papan Klip",
        testLinkHint = "Masukkan tautan Apple Maps di sini...",
        btnPasteClipboard = "Tempel",
        btnTestLink = "Uji di %s",
        testLinkConvertedLabel = "URI Tujuan Terkonversi:",
        pauseIndefinitely = "Tanpa batas",
        pause1Hour = "1 Jam",
        pause8Hours = "8 Jam",
        pauseUntilTomorrow = "Hingga besok pagi",
        dialogPauseTitle = "Pilih Durasi Jeda",
        menuSettingsAbout = "Pengaturan & Info",
        aboutTitle = "Tentang MapFlip",
        appVersionLabel = "Versi",
        btnClose = "Tutup",
        sectionLanguage = "Bahasa",
        sectionTheme = "Tampilan",
        themeSystem = "Default sistem",
        themeLight = "Terang",
        themeDark = "Gelap",
        btnDonate = "Donasi",
        donateSubtitle = "Dukung pengembangan di Ko-fi",
        privacyPolicyTitle = "Kebijakan Privasi",
        impressumTitle = "Pemberitahuan Hukum (Impressum)",
        sectionGeneral = "Umum",
        sectionAbout = "Tentang aplikasi",
        quickGuideTitle = "Panduan Penyiapan",
        btnCopyLink = "Salin tautan",
        linkCopiedToast = "Tautan disalin ke papan klip",
        btnShareLink = "Bagikan tautan",
        btnClearInput = "Hapus",
        clipboardDetectedTitle = "Tautan peta di papan klip",
        btnOpenInApp = "Buka di %s",
        actionExpand = "Bentangkan",
        actionCollapse = "Ciutkan",
        appNotInstalled = "%s tidak terinstal",
        targetAppOpenError = "Aplikasi tujuan tidak dapat dibuka",
        statusInstalled = "Terinstal",
        statusNotInstalled = "Tidak terinstal",
        tileSetupRequired = "Perlu penyiapan",
        setupSheetTitle = "Atur tautan peta",
        setupSheetSubtitle = "Android 12+ memerlukan konfirmasi tautan peta yang didukung secara manual.",
        setupStep1Title = "Buka pengaturan sistem",
        setupStep1Desc = "Ketuk tombol di bawah untuk membuka pengaturan aplikasi MapFlip.",
        setupStep2Title = "Pilih \"Buka secara default\"",
        setupStep2Desc = "Ketuk \"Buka tautan yang didukung\" atau \"Tambah tautan\".",
        setupStep3Title = "Aktifkan tautan peta",
        setupStep3Desc = "Centang semua layanan peta yang didukung (Apple, Bing, OSM, HERE, dll.).",
        setupAltTitle = "Berfungsi langsung tanpa konfigurasi:",
        setupAltShare = "Menu Berbagi: Bagikan tautan peta apa pun melalui menu Berbagi Android langsung ke MapFlip.",
        setupAltClipboard = "Papan klip: Salin tautan peta dan buka MapFlip untuk pengalihan instan.",
        setupBtnOpenSettings = "Buka pengaturan sistem",
        setupBtnDismiss = "Lanjutkan tanpa pengaturan",
        setupStatusAllActive = "%d dari %d tautan aktif",
        setupStatusPartial = "%d dari %d tautan aktif – ketuk untuk menambah lagi",
        setupStatusNone = "Tidak ada tautan aktif – konfigurasi diperlukan",
        menuSetupGuide = "Panduan Pengaturan (Android 12+)",
    )
}
